DOCKER_IMAGE: microservice-ethereum-user-actions
DOCKERFILE_PATH: ./cmd/microservice-ethereum-user-actions

SERVICES:
  - USER_ACTIONS_USDC:
      SERVICE_NAME: microservice-ethereum-user-actions-usdc
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-user-actions-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x815451bbD6C49e43fB1b614bf405E2A69A95D3Fc"
      ENV_FLU_ETHEREUM_TOKEN_NAME: USDC
      ENV_FLU_ETHEREUM_TOKEN_DECIMALS: 6

  - USER_ACTIONS_USDT:
      SERVICE_NAME: microservice-ethereum-user-actions-usdt
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-user-actions-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x777B135370b35737655a3BA7ca85bD0F08502313"
      ENV_FLU_ETHEREUM_TOKEN_NAME: USDT
      ENV_FLU_ETHEREUM_TOKEN_DECIMALS: 6

  - USER_ACTIONS_DAI:
      SERVICE_NAME: microservice-ethereum-user-actions-dai
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-user-actions-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xF7449745797B4A5932055aECF5c80AE504Bc1495"
      ENV_FLU_ETHEREUM_TOKEN_NAME: DAI
      ENV_FLU_ETHEREUM_TOKEN_DECIMALS: 18

  - USER_ACTIONS_TUSD:
      SERVICE_NAME: microservice-ethereum-user-actions-tusd
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-user-actions-tusd
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xA49BB086ca9Fa2DFbb9feE1b2033112485b743D4"
      ENV_FLU_ETHEREUM_TOKEN_NAME: TUSD
      ENV_FLU_ETHEREUM_TOKEN_DECIMALS: 18

