SERVICES:
  - PRIZE_POOL:
      SERVICE_NAME: microservice-ethereum-prize-pool
      DOCKERFILE_PATH: ./cmd/microservice-ethereum-prize-pool
      ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-prize-pool
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: aave
      ENV_FLU_ETHEREUM_AAVE_ADDRESS_PROVIDER_ADDR: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
      ENV_FLU_ETHEREUM_USD_TOKEN_ADDR: "0x13512979ADE267AB5100878E2e0f485B568328a4"
      SECRET_FLU_ETHEREUM_TOKENS_LIST: /fluidity/kovan/token_list
      SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/kovan/http_url

  - ETH_BLOCK_FLUID_TRANSERS_AMQP:
      SERVICE_NAME: microservice-ethereum-block-fluid-transfers-amqp
      DOCKERFILE_PATH: ./cmd/microservice-ethereum-block-fluid-transfers-amqp
      ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-block-fluid-transfers-amqp
      SECRET_FLU_ETHEREUM_WS_URL: /fluidity/kovan/websoket_url
      SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/kovan/http_url



  