DOCKER_IMAGE: microservice-ethereum-track-winners
DOCKERFILE_PATH: ./cmd/microservice-ethereum-track-winners
ENV_FLU_ETHEREUM_LEGACY_CONTRACT: "true"

SERVICES:
  - TRACK_WINNERS_USDC:
      SERVICE_NAME: microservice-ethereum-track-winners-usdc      
      
      ENV_FLU_WORKER_ID: ethereum-ropsten-ethereum-ropsten-microservice-ethereum-track-winners-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0X2835BED5DB82F84180ECBC7DE7C1944E154B1035"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: USDC
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6

  - TRACK_WINNERS_USDT:
      SERVICE_NAME: microservice-ethereum-track-winners-usdt
      
      ENV_FLU_WORKER_ID: ethereum-ropsten-ethereum-ropsten-microservice-ethereum-track-winners-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0X26FC224B37952BD12C792425F242E0B0A55453A6"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: USDT
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6

  - TRACK_WINNERS_DAI:
      SERVICE_NAME: microservice-ethereum-track-winners-dai
      
      ENV_FLU_WORKER_ID: ethereum-ropsten-ethereum-ropsten-microservice-ethereum-track-winners-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0X5BA8D8E005ADE3A8333CF85C3BF2A0869D606569"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: DAI
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18
