// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package govern

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CancelProposal is the `cancelProposal` instruction.
type CancelProposal struct {

	// [0] = [] governor
	//
	// [1] = [WRITE] proposal
	//
	// [2] = [SIGNER] proposer
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCancelProposalInstructionBuilder creates a new `CancelProposal` instruction builder.
func NewCancelProposalInstructionBuilder() *CancelProposal {
	nd := &CancelProposal{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetGovernorAccount sets the "governor" account.
func (inst *CancelProposal) SetGovernorAccount(governor ag_solanago.PublicKey) *CancelProposal {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(governor)
	return inst
}

// GetGovernorAccount gets the "governor" account.
func (inst *CancelProposal) GetGovernorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetProposalAccount sets the "proposal" account.
func (inst *CancelProposal) SetProposalAccount(proposal ag_solanago.PublicKey) *CancelProposal {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(proposal).WRITE()
	return inst
}

// GetProposalAccount gets the "proposal" account.
func (inst *CancelProposal) GetProposalAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetProposerAccount sets the "proposer" account.
func (inst *CancelProposal) SetProposerAccount(proposer ag_solanago.PublicKey) *CancelProposal {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(proposer).SIGNER()
	return inst
}

// GetProposerAccount gets the "proposer" account.
func (inst *CancelProposal) GetProposerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst CancelProposal) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CancelProposal,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CancelProposal) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CancelProposal) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Governor is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Proposal is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Proposer is not set")
		}
	}
	return nil
}

func (inst *CancelProposal) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CancelProposal")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("governor", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("proposal", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("proposer", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj CancelProposal) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *CancelProposal) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewCancelProposalInstruction declares a new CancelProposal instruction with the provided parameters and accounts.
func NewCancelProposalInstruction(
	// Accounts:
	governor ag_solanago.PublicKey,
	proposal ag_solanago.PublicKey,
	proposer ag_solanago.PublicKey) *CancelProposal {
	return NewCancelProposalInstructionBuilder().
		SetGovernorAccount(governor).
		SetProposalAccount(proposal).
		SetProposerAccount(proposer)
}
