// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package govern

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetGovernanceParams is the `setGovernanceParams` instruction.
type SetGovernanceParams struct {
	Params *GovernanceParameters

	// [0] = [WRITE] governor
	//
	// [1] = [SIGNER] smartWallet
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetGovernanceParamsInstructionBuilder creates a new `SetGovernanceParams` instruction builder.
func NewSetGovernanceParamsInstructionBuilder() *SetGovernanceParams {
	nd := &SetGovernanceParams{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *SetGovernanceParams) SetParams(params GovernanceParameters) *SetGovernanceParams {
	inst.Params = &params
	return inst
}

// SetGovernorAccount sets the "governor" account.
func (inst *SetGovernanceParams) SetGovernorAccount(governor ag_solanago.PublicKey) *SetGovernanceParams {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(governor).WRITE()
	return inst
}

// GetGovernorAccount gets the "governor" account.
func (inst *SetGovernanceParams) GetGovernorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *SetGovernanceParams) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *SetGovernanceParams {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(smartWallet).SIGNER()
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *SetGovernanceParams) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetGovernanceParams) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetGovernanceParams,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetGovernanceParams) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetGovernanceParams) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Governor is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
	}
	return nil
}

func (inst *SetGovernanceParams) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetGovernanceParams")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   governor", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("smartWallet", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetGovernanceParams) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetGovernanceParams) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewSetGovernanceParamsInstruction declares a new SetGovernanceParams instruction with the provided parameters and accounts.
func NewSetGovernanceParamsInstruction(
	// Parameters:
	params GovernanceParameters,
	// Accounts:
	governor ag_solanago.PublicKey,
	smartWallet ag_solanago.PublicKey) *SetGovernanceParams {
	return NewSetGovernanceParamsInstructionBuilder().
		SetParams(params).
		SetGovernorAccount(governor).
		SetSmartWalletAccount(smartWallet)
}
