FROM node:20-alpine3.18@sha256:6a5e5331ad99c311f0fa58bf838e9d5bb1c9fc940977149759f48d8e92029d07

RUN apk add --no-cache make

COPY --from=fluidity/build-container /usr/local/bin/wait-for-database.sh /usr/local/bin
COPY --from=fluidity/build-container /usr/local/bin/wait-for-amqp /usr/local/bin
COPY --from=fluidity/build-container /usr/local/bin/wait-for-ws /usr/local/bin

WORKDIR /usr/local/src/fluidity

COPY build.mk .
COPY node.mk .

