
FROM fluidity/build-container-root:latest

RUN apt-get update && \
	apt-get install -qy nginx

WORKDIR /usr/local/src/fluidity

COPY build.mk .
COPY golang.mk .
COPY node.mk .
COPY web.mk .

COPY web web
