
FROM alpine:3.18 AS build

RUN apk add --no-cache \
	nodejs \
	npm \
	yarn \
	make \
	libc6-compat \
	python3 \
	build-base

# Libc6-compat is needed for Turbo to work
# Python/Build-base to remain platform agnostic (node-gyp pre-requisite)

RUN npm install -g turbo
