
FROM fluidity/build-container:latest

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -

RUN apt-get update && \
	apt-get install -y nodejs nginx

WORKDIR /usr/local/src/fluidity

COPY web.mk .

COPY web web
