
# Aligned with build-root (golang1.20-alpine3.18)
FROM alpine:3.18.6@sha256:695ae78b4957fef4e53adc51febd07f5401eb36fcd80fff3e5107a2b4aa42ace AS build

RUN apk add --no-cache \
	nodejs \
	npm \
	yarn \
	make \
	libc6-compat \
	python3 \
	build-base

# Libc6-compat is needed for Turbo to work
# Python/Build-base to remain platform agnostic (node-gyp pre-requisite)

RUN npm install -g turbo
