FROM alpine:3.19

RUN apk add --no-cache \
    nodejs \
    npm \
    yarn \
    nginx \
    libc6-compat

# Libc6-compat is needed for Turbo to work

RUN npm -g install \
    sharp

COPY automation/nginx-default.conf /etc/nginx/http.d/default.conf
