# Aligned with build-root (golang1.20-alpine3.18)
FROM alpine:3.18.6@sha256:695ae78b4957fef4e53adc51febd07f5401eb36fcd80fff3e5107a2b4aa42ace AS build

RUN apk add --no-cache postgresql-client

COPY --from=fluidity/build-container /usr/local/bin/wait-for-database.sh /usr/local/bin
COPY --from=fluidity/build-container /usr/local/bin/wait-for-amqp /usr/local/bin
COPY --from=fluidity/build-container /usr/local/bin/wait-for-ws /usr/local/bin

