SERVICES:
  - PRIZE_POOL:
      SERVICE_NAME: microservice-solana-prize-pool
      DOCKERFILE_PATH: ./cmd/microservice-solana-prize-pool
      ENV_FLU_WORKER_ID: solana-devnet-microservice-solana-prize-pool
      ENV_FLU_SOLANA_PROGRAM_ID: GjRwsHMgCAX2QUrw64tyT9RQhqm28fmntNAjgxoaTztU
      SECRET_FLU_SOLANA_TOKENS_LIST: /fluidity/solana/token_list
      ENV_FLU_SOLANA_PRIZE_POOL_UPDATE_TIME: 1m
      ENV_FLU_SOLANA_TVL_DATA_PUBKEY: CAKG5gr5ZFGyEXb98pXMqUCdu8gqc5VtXxXkonpcZixW
      ENV_FLU_SOLANA_SOLEND_PROGRAM_ID: ALend7Ketfx5bxh6ghsCDXAoDrhvEmsXT3cynB6aPLgx
      SECRET_FLU_SOLANA_RPC_URL: /fluidity/solana/rpc_url
      SECRET_FLU_SOLANA_TVL_PAYER_PRIKEY: /fluidity/solana/tvl_payer_prikey
