import { Provider } from "@fluidity-money/surfing";

const providerNames: { [K: string]: Provider } = {
  Aave: "Aave",
  aave: "Aave",
  Aldrin: "Aldrin",
  aldrin: "Aldrin",
  aldrinv1: "Aldrin",
  aldrinv2: "Aldrin",
  Circle: "Circle",
  circle: "Circle",
  Compound: "Compound",
  compound: "Compound",
  Dodo: "Dodo",
  dodo: "Dodo",
  dodo_v2: "Dodo",
  Jupiter: "Jupiter",
  jupiter: "Jupiter",
  Lemniscap: "Lemniscap",
  lemniscap: "Lemniscap",
  Maker: "Maker",
  maker: "Maker",
  Multicoin: "Multicoin",
  multicoin: "Multicoin",
  Orca: "Orca",
  orca: "Orca",
  Polygon: "Polygon",
  polygon: "Polygon",
  Saber: "Saber",
  saber: "Saber",
  Solana: "Solana",
  solana: "Solana",
  Solend: "Solend",
  solend: "Solend",
  Uniswap: "Uniswap",
  uniswap: "Uniswap",
  uniswap_v2: "Uniswap",
  Sushiswap: "Sushiswap",
  sushiswap: "Sushiswap",
  Fluidity: "Fluidity",
  fluidity: "Fluidity",
  spl: "Fluidity",
  none: "Fluidity",
  Oneinch: "Oneinch",
  oneinch: "Oneinch",
  "1inch": "Oneinch",
  oneinch_v1: "Oneinch",
  oneinch_v2: "Oneinch",
  oneinch_fixedrate: "Oneinch",
  Balancer: "Balancer",
  balancer: "Balancer",
  balancer_v2: "Balancer",
  Mooniswap: "Mooniswap",
  mooniswap: "Mooniswap",
  Curve: "Curve",
  curve: "Curve",
  Multichain: "Multichain",
  multichain: "Multichain",
  "XY Finance": "XY Finance",
  "xy finance": "XY Finance",
  xy: "XY Finance",
  xy_finance: "XY Finance",
  Raydium: "Raydium",
  raydium: "Raydium",
  Lifinity: "Lifinity",
  lifinity: "Lifinity",
  Mercurial: "Mercurial",
  mercurial: "Mercurial",
};

export const getProviderDisplayName = (name: string) => {
  return providerNames[name];
};
