SERVICES:
  - COMMON_RABBITMQ_BACKLOG_CHECKER:
      SERVICE_NAME: microservice-common-rabbitmq-backlog-checker-ethereum
      DOCKER_IMAGE: microservice-common-rabbitmq-backlog-checker
      DOCKERFILE_PATH: ./cmd/microservice-common-rabbitmq-backlog-checker
      DEPLOYMENT_TYPE: CRON

      ENV_FLU_WORKER_ID: ethereum-staging-microservice-common-rabbitmq-backlog-checker
      SECRET_FLU_AMQP_QUEUE_ADDR
      SECRET_FLU_DISCORD_WEBHOOK: /fluidity/discord/webhook

      EVENT_ROLE: ecsEventsRole
      EVENT_RULE: microservice-common-rabbitmq-backlog-checker-ethereum-cron
      EVENT_SCHEDULE: rate(5 minutes) #every 5mins
