DOCKER_IMAGE: microservice-ethereum-application-server
DOCKERFILE_PATH: ./cmd/microservice-ethereum-application-server
SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ropsten/http_url

SERVICES:
  - APPSERVER_USDT:
      SERVICE_NAME: microservice-ethereum-application-server-usdt
      ENV_FLU_WORKER_ID: production-microservice-ethereum-application-server-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x26FC224B37952Bd12C792425F242E0B0a55453a6"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6

  - APPSERVER_USDC:
      SERVICE_NAME: microservice-ethereum-application-server-usdc
      ENV_FLU_WORKER_ID: production-microservice-ethereum-application-server-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x2835Bed5dB82f84180eCBC7dE7C1944E154b1035"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6

  - APPSERVER_DAI:
      SERVICE_NAME: microservice-ethereum-application-server-dai
      ENV_FLU_WORKER_ID: production-microservice-ethereum-application-server-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x5BA8d8e005aDe3A8333CF85c3bf2A0869d606569"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18


