SERVICES:
  - FRONTEND_APP:
      SERVICE_NAME: fluidity-money-app
      DOCKER_IMAGE: app.fluidity.money-frontend
      DOCKERFILE_PATH: ./web/app.fluidity.money
      CPU_LIMIT: 512
      MEM_LIMIT: 1024
      DEPLOYMENT_TYPE: CODEDEPLOY
      CODEDEPLOY_WAIT_TIME: 30 #minutes
      LOAD_BALANCER: flu-dev-app-fluidity-alb
      TARGET_GROUP_01: flu-dev-app-fluidity-fe-tg-01
      TARGET_GROUP_02: flu-dev-app-fluidity-fe-tg-02
      SECRET_BITQUERY_TOKEN: /fluidity/bitquery_token
      SECRET_FLU_ETH_RPC_HTTP: /fluidity/ethereum/http_url
      SECRET_FLU_ETH_RPC_WS: /fluidity/ethereum/websocket_url
      SECRET_FLU_SOL_RPC_HTTP: /fluidity/solana/http_url
      SECRET_FLU_SOL_RPC_WS: /fluidity/solana/websocket_url
      SECRET_FLU_HASURA_HTTP: /fluidity/hasura/rpc_http
      SECRET_FLU_HASURA_WS: /fluidity/hasura/rpc_ws
      SECRET_FLU_HASURA_SECRET: /fluidity/hasura/key

      DOCKER_ARGS:
        SECRET_REACT_APP_SENTRY_DSN: /fluidity/frontend/sentryURL
        SECRET_GITHUB_TOKEN: /fluidity/npm/github_token

