DOCKER_IMAGE: microservice-ethereum-worker-server
DOCKERFILE_PATH: ./cmd/microservice-ethereum-worker-server
ENV_FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR: "0x65c816077C29b557BEE980ae3cC2dCE80204A0C5"
SECRET_FLU_ETHEREUM_APPLICATION_CONTRACTS: /fluidity/ethereum/application_contracts
SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ethereum/http_url

SERVICES:
  - WORKER_SERVER_USDT:
      SERVICE_NAME: microservice-ethereum-worker-server-usdt
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x777B135370b35737655a3BA7ca85bD0F08502313"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: USDT
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6
      ENV_FLU_ETHEREUM_CTOKEN_ADDR: "0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9"
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: compound
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdt
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.usdt.apy.moving-average

  - WORKER_SERVER_USDC:
      SERVICE_NAME: microservice-ethereum-worker-server-usdc
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x815451bbD6C49e43fB1b614bf405E2A69A95D3Fc"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: USDC
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6
      ENV_FLU_ETHEREUM_CTOKEN_ADDR: "0x39AA39c021dfbaE8faC545936693aC917d5E7563"
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: compound
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdc
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.usdc.apy.moving-average

  - WORKER_SERVER_DAI:
      SERVICE_NAME: microservice-ethereum-worker-server-dai
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xF7449745797B4A5932055aECF5c80AE504Bc1495"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: DAI
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18
      ENV_FLU_ETHEREUM_CTOKEN_ADDR: "0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643"
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: compound
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.dai
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.dai.apy.moving-average

  - WORKER_SERVER_TUSD:
      SERVICE_NAME: microservice-ethereum-worker-server-tusd
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-tusd
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xA49BB086ca9Fa2DFbb9feE1b2033112485b743D4"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: TUSD
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18
      ENV_FLU_ETHEREUM_CTOKEN_ADDR: "0x12392f67bdf24fae0af363c24ac620a2f67dad86"
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: compound
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.tusd
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.tusd.apy.moving-average

  - WORKER_SERVER_FRAX:
      SERVICE_NAME: microservice-ethereum-worker-server-frax
      ENV_FLU_WORKER_ID: ethereum-staging-microsrvice-ethereum-worker-server-frax
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xeDfE9eD77162e7EA830FC4aE8a892b7E4b8D4940"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: FRAX
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18
      ENV_FLU_ETHEREUM_ATOKEN_ADDR: "0xd4937682df3C8aEF4FE912A96A74121C0829E664"
      ENV_FLU_ETHEREUM_USD_TOKEN_ADDR: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      ENV_FLU_ETHEREUM_ETH_TOKEN_ADDR: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: aave
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.frax
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.frax.apy.moving-average

  - WORKER_SERVER_FEI:
      SERVICE_NAME: microservice-ethereum-worker-server-fei
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-fei
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x3cd03e4016d3DD590AFD524daBede7609EC357CA"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: FEI
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18
      ENV_FLU_ETHEREUM_ATOKEN_ADDR: "0x683923dB55Fead99A79Fa01A27EeC3cB19679cC3"
      ENV_FLU_ETHEREUM_USD_TOKEN_ADDR: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      ENV_FLU_ETHEREUM_ETH_TOKEN_ADDR: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
      ENV_FLU_ETHEREUM_TOKEN_BACKEND: aave
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.fei
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.fei.apy.moving-average