SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/kovan/http_url
DOCKER_IMAGE: microservice-ethereum-worker-server
DOCKERFILE_PATH: ./cmd/microservice-ethereum-worker-server
ENV_FLU_ETHEREUM_TOKEN_BACKEND: aave
ENV_FLU_ETHEREUM_AAVE_ADDRESS_PROVIDER_ADDR: "0x88757f2f99175387aB4C6a4b3067c77A695b0349"
ENV_FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR: "0XBEF4E076A995C784BE6094A432B9CA99B7431A3F"
ENV_FLU_ETHEREUM_ETH_TOKEN_ADDR: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
ENV_FLU_ETHEREUM_USD_TOKEN_ADDR: "0x13512979ADE267AB5100878E2e0f485B568328a4"

SERVICES:
  - WORKER_SERVER_USDT:
      SERVICE_NAME: microservice-ethereum-worker-server-usdt
      ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-worker-server-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x47eD7c59A487dd907de2986e0F95F8CC4Dc8CCf6"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_ADDR: "0x13512979ADE267AB5100878E2e0f485B568328a4"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: USDT
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6
      ENV_FLU_ETHEREUM_ATOKEN_ADDR: "0xFF3c8bc103682FA918c954E84F5056aB4DD5189d"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdt
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.usdt.apy.moving-average

  - WORKER_SERVER_USDC:
      SERVICE_NAME: microservice-ethereum-worker-server-usdc
      ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-worker-server-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x2f2204738CC4dCf1ec2d88369AB5B7e16a7C7035"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_ADDR: "0xe22da380ee6B445bb8273C81944ADEB6E8450422"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: USDC
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 6
      ENV_FLU_ETHEREUM_ATOKEN_ADDR: "0xe12AFeC5aa12Cf614678f9bFeeB98cA9Bb95b5B0"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdc
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.usdc.apy.moving-average

  - WORKER_SERVER_DAI:
      SERVICE_NAME: microservice-ethereum-worker-server-dai
      ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-worker-server-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xA4c2826Df07f0a37B125D5815B12Ff2f529a66e9"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_ADDR: "0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: DAI
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18
      ENV_FLU_ETHEREUM_ATOKEN_ADDR: "0xdCf0aF9e59C002FA3AA091a46196b37530FD48a8"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.dai
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.dai.apy.moving-average

  - WORKER_SERVER_TUSD:
      SERVICE_NAME: microservice-ethereum-worker-server-tusd
      ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-worker-server-tusd
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xcD20E20e5b873ecc92d284515C6254F386c7C57B"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_ADDR: "0x016750AC630F711882812f24Dba6c95b9D35856d"
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_NAME: TUSD
      ENV_FLU_ETHEREUM_UNDERLYING_TOKEN_DECIMALS: 18
      ENV_FLU_ETHEREUM_ATOKEN_ADDR: "0x39914AdBe5fDbC2b9ADeedE8Bcd444b20B039204"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.tusd
      ENV_FLU_ETHEREUM_REDIS_APY_MOVING_AVERAGE_KEY: ethereum.worker.tusd.apy.moving-average