SERVICES:
  - COMMON_RABBITMQ_BACKLOG_CHECKER:
      SERVICE_NAME: microservice-common-rabbitmq-backlog-checker-ethereum
      DOCKER_IMAGE: microservice-common-rabbitmq-backlog-checker
      DOCKERFILE_PATH: ./cmd/microservice-common-rabbitmq-backlog-checker
      DEPLOYMENT_TYPE: CRON

      ENV_FLU_WORKER_ID: ethereum-ropsten-microservice-common-rabbitmq-backlog-checker
      ENV_FLU_RABBIT_MAX_DEAD_LETTER: 0
      SECRET_FLU_AMQP_QUEUE_ADDR: /fluidity/data/rabbitmq/client_uri
      SECRET_FLU_DISCORD_WEBHOOK: /fluidity/discord/webhook

      EVENT_ROLE: ecsEventsRole
      EVENT_RULE: microservice-common-rabbitmq-backlog-checker-ethereum-cron
      EVENT_SCHEDULE: rate(1 hour) #every 1hr
