DOCKER_IMAGE: microservice-solana-user-actions
DOCKERFILE_PATH: ./cmd/microservice-solana-user-actions
ENV_FLU_SOLANA_PROGRAM_ID: HEvunKKgzf4SMZimVMET6HuzAyfGJS4ZMShUz94KLUdR
ENV_FLU_SOLANA_TOKEN_DECIMALS: 6

SERVICES:
  - ACTIONS_USDC:
      SERVICE_NAME: microservice-solana-user-actions-usdc
      ENV_FLU_WORKER_ID: solana-staging-microservice-solana-user-actions-usdc
      ENV_FLU_SOLANA_FLUID_MINT_PUBKEY: Ez2zVjw85tZan1ycnJ5PywNNxR6Gm4jbXQtZKyQNu3Lv
      ENV_FLU_SOLANA_PDA_PUBKEY: CBrYRFyEwyn9gMPVFbRBwfcoU6JnViTEBaYyvFZGgZnc
      ENV_FLU_SOLANA_TOKEN_SHORT_NAME: USDC

  - ACTIONS_USDT:
      SERVICE_NAME: microservice-solana-user-actions-usdt
      ENV_FLU_WORKER_ID: solana-staging-microservice-solana-user-actions-usdt
      ENV_FLU_SOLANA_FLUID_MINT_PUBKEY: D5zHHS5tkf9zfGBRPQbDKpUiRAMVK8VvxGwTHP6tP1B8
      ENV_FLU_SOLANA_PDA_PUBKEY: 5tCSTEkozvUw9YZxZzsGkR9upMQNacFEBiYN21nfCj77
      ENV_FLU_SOLANA_TOKEN_SHORT_NAME: USDT

  - ACTIONS_UXD:
      SERVICE_NAME: microservice-solana-user-actions-uxd
      ENV_FLU_WORKER_ID: solana-staging-microservice-solana-user-actions-uxd
      ENV_FLU_SOLANA_FLUID_MINT_PUBKEY: 7Taua7k6kX2UTD1joXTsyQ8jodAzUEjmxXfCn5zvU55m
      ENV_FLU_SOLANA_PDA_PUBKEY: FwdhT2Q3dckz2EfLoKznsBm5V55uk88ZtM5ep45NuoJJ
      ENV_FLU_SOLANA_TOKEN_SHORT_NAME: UXD
