
DOCKER_IMAGE: microservice-ethereum-worker-sender
DOCKERFILE_PATH: ./cmd/microservice-ethereum-worker-sender
ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/kovan/http_url
ENV_FLU_ETHEREUM_WS_URL: wss://kovan.ethereum.fluidity.money:8081/updates
ENV_FLU_ETHEREUM_LEGACY_CONTRACT: "true"

SERVICES:
 - SENDER_USDC:
    SERVICE_NAME: microservice-ethereum-worker-sender-usdc
    ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-worker-sender-usdc
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x2f2204738CC4dCf1ec2d88369AB5B7e16a7C7035"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/kovan/usdc/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.usdc

 - SENDER_USDT:
    SERVICE_NAME: microservice-ethereum-worker-sender-usdt
    ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-worker-sender-usdt
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x2f2204738CC4dCf1ec2d88369AB5B7e16a7C7035"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/kovan/usdt/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.usdt

 - SENDER_DAI:
    SERVICE_NAME: microservice-ethereum-worker-sender-dai
    ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-worker-sender-dai
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x47eD7c59A487dd907de2986e0F95F8CC4Dc8CCf6"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/kovan/dai/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.dai

 - SENDER_TUSD:
    SERVICE_NAME: microservice-ethereum-worker-sender-tusd
    ENV_FLU_WORKER_ID: ethereum-kovan-microservice-ethereum-worker-sender-tusd
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xcD20E20e5b873ecc92d284515C6254F386c7C57B"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/kovan/tusd/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.tusd


