
FROM postgres:14.0-alpine

ENV REPO /usr/src/fluidity-migrations-postgres

RUN apk add make

RUN mkdir ${REPO}

WORKDIR ${REPO}

COPY . ${REPO}

RUN make up-postgres

COPY init-postgres-db.sh /docker-entrypoint-initdb.d/init-sqls.sh

