
FROM timescale/timescaledb:latest-pg12

ENV REPO /usr/src/fluidity-migrations-timescale

RUN apk add make

RUN mkdir ${REPO}

WORKDIR ${REPO}

COPY . ${REPO}

RUN make up-timescale

COPY init-timescale-db.sh /docker-entrypoint-initdb.d/init-sqls.sh
