DOCKERFILE_PATH: ./web/ethereum.fluidity.money

SERVICES:
  - FLUIDITY_FRONTEND:
      SERVICE_NAME: ethereum-fluidity-money-frontend
      DOCKER_IMAGE: ethereum.fluidity.money-frontend
      TARGET_GROUP: flu-staging-eth-fe-tg
      
      DOCKER_ARGS:
        REACT_APP_API_URL: https://staging.ethereum.fluidity.money:8081
        REACT_APP_WALLET_CONNECT_GETH_URI: wss://staging.ethereum.fluidity.money:8081
        REACT_APP_WEBSOCKET: wss://staging.ethereum.fluidity.money:8081/updates
        REACT_APP_CHAIN_ID: 1
        REACT_APP_TOKEN_CONFIG_FILE: staging-mainnet-tokens.json

  - FLUIDITY_BACKEND:
      SERVICE_NAME: ethereum-fluidity-money-backend
      DOCKER_IMAGE: ethereum.fluidity.money-backend
      TARGET_GROUP: flu-staging-eth-be-tg

      ENV_FLU_WORKER_ID: ethereum-staging-ethereum.fluidity.money-backend
      ENV_FLU_ETHEREUM_CHAIN_ID: 1
      SECRET_FLU_ETHEREUM_TOKENS_LIST: /fluidity/ethereum/token_list
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY_LIST: /fluidity/ethereum/private_key_list
      SECRET_FLU_DISCORD_WEBHOOK: /fluidity/discord/webhook


