
FROM fluidity/go-docker:latest

ENV REPO ethereum-testnet-faucet

ENV DIR /usr/src/${REPO}

COPY . ${DIR}

WORKDIR ${DIR}

RUN make backend

ENTRYPOINT [ \
	"wait-for-amqp", \
	"wait-for-database.sh", \
	"./ethereum-testnet-faucet" \
]
