SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ropsten/http_url
DOCKER_IMAGE: microservice-ethereum-worker-client
DOCKERFILE_PATH: ./cmd/microservice-ethereum-worker-client

SERVICES:
  - WORKER_CLIENT_USDT:
      SERVICE_NAME: microservice-ethereum-worker-client-usdt
      
      ENV_FLU_WORKER_ID: ethereum-ropsten-ethereum-ropsten-microservice-ethereum-worker-server-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0X26FC224B37952BD12C792425F242E0B0A55453A6"
      ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
      ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdt
      ENV_FLU_ETHEREUM_AMQP_PUBLISH_NAME: ethereum.winners.usdt
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ropsten/usdt/private_key

  - WORKER_CLIENT_USDC:
      SERVICE_NAME: microservice-ethereum-worker-client-usdc

      ENV_FLU_WORKER_ID: ethereum-ropsten-ethereum-ropsten-microservice-ethereum-worker-server-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0X2835BED5DB82F84180ECBC7DE7C1944E154B1035"
      ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
      ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdc
      ENV_FLU_ETHEREUM_AMQP_PUBLISH_NAME: ethereum.winners.usdc
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ropsten/usdc/private_key

  - WORKER_CLIENT_DAI:
      SERVICE_NAME: microservice-ethereum-worker-client-dai
      
      ENV_FLU_WORKER_ID: ethereum-ropsten-ethereum-ropsten-microservice-ethereum-worker-server-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0X5BA8D8E005ADE3A8333CF85C3BF2A0869D606569"
      ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
      ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.dai
      ENV_FLU_ETHEREUM_AMQP_PUBLISH_NAME: ethereum.winners.dai
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ropsten/dai/private_key

