DOCKER_IMAGE: microservice-ethereum-worker-client
DOCKERFILE_PATH: ./cmd/microservice-ethereum-worker-client
ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ethereum/http_url

SERVICES:
  - WORKER_CLIENT_USDT:
      SERVICE_NAME: microservice-ethereum-worker-client-usdt
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-usdt
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x777B135370b35737655a3BA7ca85bD0F08502313"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdt
      ENV_FLU_ETHEREUM_AMQP_PUBLISH_NAME: ethereum.winners.usdt
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/usdt/private_key

  - WORKER_CLIENT_USDC:
      SERVICE_NAME: microservice-ethereum-worker-client-usdc
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-usdc
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x815451bbD6C49e43fB1b614bf405E2A69A95D3Fc"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.usdc
      ENV_FLU_ETHEREUM_AMQP_PUBLISH_NAME: ethereum.winners.usdc
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/usdc/private_key

  - WORKER_CLIENT_DAI:
      SERVICE_NAME: microservice-ethereum-worker-client-dai
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-dai
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xF7449745797B4A5932055aECF5c80AE504Bc1495"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.dai
      ENV_FLU_ETHEREUM_AMQP_PUBLISH_NAME: ethereum.winners.dai
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/dai/private_key

  - WORKER_CLIENT_TUSD:
      SERVICE_NAME: microservice-ethereum-worker-client-tusd
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-tusd
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xA49BB086ca9Fa2DFbb9feE1b2033112485b743D4"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.tusd
      ENV_FLU_ETHEREUM_AMQP_PUBLISH_NAME: ethereum.winners.tusd
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/tusd/private_key

  - WORKER_CLIENT_FRAX:
      SERVICE_NAME: microservice-ethereum-worker-client-frax
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-frax
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xeDfE9eD77162e7EA830FC4aE8a892b7E4b8D4940"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.frax
      ENV_FLU_ETHEREUM_AMQP_PUBLISH_NAME: ethereum.winners.frax
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/frax/private_key

  - WORKER_CLIENT_FEI:
      SERVICE_NAME: microservice-ethereum-worker-client-fei
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-server-fei
      ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x3cd03e4016d3DD590AFD524daBede7609EC357CA"
      ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.worker.fei
      ENV_FLU_ETHEREUM_AMQP_PUBLISH_NAME: ethereum.winners.fei
      SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/fei/private_key

