FROM fluidity/build-container:latest AS build

WORKDIR /usr/local/src/fluidity/web/faucet.fluidity.money

COPY . .
RUN make backend

FROM fluidity/runtime-container:latest

COPY --from=build /usr/local/src/fluidity/web/faucet.fluidity.money/faucet.fluidity.money.o .

ENTRYPOINT [ \
	"wait-for-amqp", \
	"wait-for-database.sh", \
	"./faucet.fluidity.money.o" \
]

