
DOCKER_IMAGE: microservice-ethereum-worker-sender
DOCKERFILE_PATH: ./cmd/microservice-ethereum-worker-sender
ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ropsten/http_url
ENV_FLU_ETHEREUM_WS_URL: wss://ropsten.ethereum.fluidity.money:8081/updates

SERVICES:
 - SENDER_USDC:
    SERVICE_NAME: microservice-ethereum-worker-sender-usdc
    ENV_FLU_WORKER_ID: ethereum-ropsten-microservice-ethereum-worker-sender-usdc
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0X2835BED5DB82F84180ECBC7DE7C1944E154B1035"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ropsten/usdc/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.usdc

 - SENDER_USDT:
    SERVICE_NAME: microservice-ethereum-worker-sender-usdt
    ENV_FLU_WORKER_ID: ethereum-ropsten-microservice-ethereum-worker-sender-usdt
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0X26FC224B37952BD12C792425F242E0B0A55453A6"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ropsten/usdt/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.usdt

 - SENDER_DAI:
    SERVICE_NAME: microservice-ethereum-worker-sender-dai
    ENV_FLU_WORKER_ID: ethereum-ropsten-microservice-ethereum-worker-sender-dai
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0X5BA8D8E005ADE3A8333CF85C3BF2A0869D606569"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ropsten/dai/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.dai


