
DOCKER_IMAGE: microservice-ethereum-worker-sender
DOCKERFILE_PATH: ./cmd/microservice-ethereum-worker-sender
ENV_FLU_ETHEREUM_GAS_LIMIT: 8000000
SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ethereum/http_url
ENV_FLU_ETHEREUM_WS_URL: wss://backend.staging.ethereum.fluidity.money/updates
ENV_FLU_ETHEREUM_LEGACY_CONTRACT: "true"

SERVICES:
 - SENDER_USDC:
    SERVICE_NAME: microservice-ethereum-worker-sender-usdc
    ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-sender-usdc
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x815451bbD6C49e43fB1b614bf405E2A69A95D3Fc"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/usdc/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.usdc

 - SENDER_USDT:
    SERVICE_NAME: microservice-ethereum-worker-sender-usdt
    ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-sender-usdt
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x777B135370b35737655a3BA7ca85bD0F08502313"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/usdt/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.usdt

 - SENDER_DAI:
    SERVICE_NAME: microservice-ethereum-worker-sender-dai
    ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-sender-dai
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xF7449745797B4A5932055aECF5c80AE504Bc1495"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/dai/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.dai

 - SENDER_TUSD:
    SERVICE_NAME: microservice-ethereum-worker-sender-tusd
    ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-sender-tusd
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xA49BB086ca9Fa2DFbb9feE1b2033112485b743D4"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/tusd/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.tusd

 - SENDER_FRAX:
    SERVICE_NAME: microservice-ethereum-worker-sender-frax
    ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-sender-frax
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0xeDfE9eD77162e7EA830FC4aE8a892b7E4b8D4940"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/frax/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.frax

 - SENDER_FEI:
    SERVICE_NAME: microservice-ethereum-worker-sender-fei
    ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-worker-sender-fei
    ENV_FLU_ETHEREUM_CONTRACT_ADDR: "0x3cd03e4016d3DD590AFD524daBede7609EC357CA"
    SECRET_FLU_ETHEREUM_WORKER_PRIVATE_KEY: /fluidity/ethereum/fei/private_key
    ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
    ENV_FLU_ETHEREUM_AMQP_QUEUE_NAME: ethereum.winners.batched.fei


