
import { mainDeployTransparentUpgradeableProxy } from "./transparent-upgradeable-proxy";

mainDeployTransparentUpgradeableProxy("LootboxStaking", [
  "FLU_ARBITRUM_OPERATOR_ADDRESS",
  "FLU_ARBITRUM_EMERGENCY_COUNCIL_ADDRESS",
  "FLU_ARBITRUM_FUSDC_ADDRESS",
  "FLU_ARBITRUM_USDC_ADDRESS",
  "FLU_ARBITRUM_WETH_ADDRESS",
  "FLU_ARBITRUM_CAMELOT_ROUTER",
  "FLU_ARBITRUM_SUSHIWAP_BENTO_BOX",
  "FLU_ARBITRUM_CAMELOT_FUSDC_USDC_PAIR",
  "FLU_ARBITRUM_CAMELOT_FUSDC_WETH_PAIR",
  "FLU_ARBITRUM_SUSHISWAP_FUSDC_USDC_POOL",
  "FLU_ARBITRUM_SUSHISWAP_FUSDC_WETH_POOL"
]).then(_ => {});
