
import { mainDeployTransparentUpgradeableProxy } from "./transparent-upgradeable-proxy";

mainDeployTransparentUpgradeableProxy("LootboxStaking", [
  `FLU_ARBITRUM_OPERATOR_ADDRESS`,
  `FLU_ARBITRUM_EMERGENCY_COUNCIL_ADDRESS`,
  `FLU_ARBITRUM_FUSDC_ADDRESS`,
  `FLU_ARBITRUM_USDC_ADDRESS`,
  `FLU_ARBITRUM_WETH_ADDRESS`,
  `FLU_ARBITRUM_CAMELOT_ROUTER`,
  `FLU_ARBITRUM_SUSHIWAP_BENTO_BOX`,
  `FLU_ARBITRUM_CAMELOT_FUSDC_USDC`,
  `FLU_ARBITRUM_CAMELOT_FUSDC_WETH`
]).then(_ => {});
