DOCKER_IMAGE: microservice-solana-worker-client
DOCKERFILE_PATH: ./cmd/microservice-solana-worker-client
ENV_FLU_SOLANA_PROGRAM_ID: HEvunKKgzf4SMZimVMET6HuzAyfGJS4ZMShUz94KLUdR
ENV_FLU_SOLANA_TVL_DATA_PUBKEY: B6xiDeQ9gNHdM4XG1VqHwyFR3AqUukKAzzhDFJirkgqP
ENV_FLU_SOLANA_SOLEND_PROGRAM_ID: So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo
ENV_FLU_SOLANA_TOKEN_DECIMALS: 6
SECRET_FLU_SOLANA_PAYER_PRIKEY: /fluidity/solana/payer_prikey
SECRET_FLU_SOLANA_RPC_URL: /fluidity/solana/rpc_url

SERVICES:
  - CLIENT_USDC:
      SERVICE_NAME: microservice-solana-worker-client-usdc
      ENV_FLU_WORKER_ID: solana-staging-microservice-solana-worker-client-usdc
      ENV_FLU_SOLANA_FLUID_MINT_PUBKEY: Ez2zVjw85tZan1ycnJ5PywNNxR6Gm4jbXQtZKyQNu3Lv
      ENV_FLU_SOLANA_OBLIGATION_PUBKEY: J6ZHkcCiAKSKTmoUZzozZ2L1Wwm34WF2VQamyu2Sno6A
      ENV_FLU_SOLANA_RESERVE_PUBKEY: BgxfHJDzm44T7XG68MYKx7YisTjZu73tVovyZSjJMpmw
      ENV_FLU_SOLANA_PYTH_PUBKEY: Gnt27xtC473ZT2Mw5u8wZ68Z3gULkSTb5DuxJy7eJotD
      ENV_FLU_SOLANA_SWITCHBOARD_PUBKEY: CZx29wKMUxaJDq6aLVQTdViPL754tTR64NAgQBUGxxHb
      ENV_FLU_SOLANA_TOKEN_NAME: USDC
      ENV_FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.usdc.winners
  
  - CLIENT_USDT:
      SERVICE_NAME: microservice-solana-worker-client-usdt
      ENV_FLU_WORKER_ID: solana-staging-microservice-solana-worker-client-usdt
      ENV_FLU_SOLANA_FLUID_MINT_PUBKEY: D5zHHS5tkf9zfGBRPQbDKpUiRAMVK8VvxGwTHP6tP1B8
      ENV_FLU_SOLANA_OBLIGATION_PUBKEY: 446FsyYfANPuiK18DYGLwQm6B5b2MecTUvm1KtnDMGca
      ENV_FLU_SOLANA_RESERVE_PUBKEY: 8K9WC8xoh2rtQNY7iEGXtPvfbDCi563SdWhCAhuMP2xE
      ENV_FLU_SOLANA_PYTH_PUBKEY: 3vxLXJqLqF3JG5TCbYycbKWRBbCJQLxQmBGCkyqEEefL
      ENV_FLU_SOLANA_SWITCHBOARD_PUBKEY: 5mp8kbkTYwWWCsKSte8rURjTuyinsqBpJ9xAQsewPDD
      ENV_FLU_SOLANA_TOKEN_NAME: USDT
      ENV_FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.usdt.winners

  - CLIENT_UXD:
      SERVICE_NAME: microservice-solana-worker-client-uxd
      ENV_FLU_WORKER_ID: solana-staging-microservice-solana-worker-client-uxd
      ENV_FLU_SOLANA_FLUID_MINT_PUBKEY: 7Taua7k6kX2UTD1joXTsyQ8jodAzUEjmxXfCn5zvU55m
      ENV_FLU_SOLANA_OBLIGATION_PUBKEY: HH4BzUBsKwenYsGQfYB6Tyj739XXxxjFVE6oMZ6xiDsY
      ENV_FLU_SOLANA_RESERVE_PUBKEY: 27YJsVpHWvjS8BKaz7Gd8unSFJAMrh6gPEFjqhYxn9AE
      ENV_FLU_SOLANA_PYTH_PUBKEY: nu11111111111111111111111111111111111111111
      ENV_FLU_SOLANA_SWITCHBOARD_PUBKEY: Lj3y2beRYhCaQQH9SYjmMJv3uuTcqpCJjQYe4829FAL
      ENV_FLU_SOLANA_TOKEN_NAME: UXD
      ENV_FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.uxd.winners
