DOCKER_IMAGE: microservice-solana-user-actions
DOCKERFILE_PATH: ./cmd/microservice-solana-user-actions
ENV_FLU_SOLANA_PROGRAM_ID: GjRwsHMgCAX2QUrw64tyT9RQhqm28fmntNAjgxoaTztU
ENV_FLU_SOLANA_TOKEN_DECIMALS: 6

SERVICES:
  - ACTIONS_USDC:
      SERVICE_NAME: microservice-solana-user-actions-usdc
      ENV_FLU_WORKER_ID: solana-devnet-microservice-solana-user-actions-usdc
      ENV_FLU_SOLANA_FLUID_MINT_PUBKEY: 2XGVdHsAiMM9QDM9tV4fwQ2JnyWdSJaiXp2KifLJD1oa
      ENV_FLU_SOLANA_PDA_PUBKEY: F3bNiT1rmu1Aqt6o43miDuXh9v7M6BAqysS96Tik2NKe
      ENV_FLU_SOLANA_TOKEN_SHORT_NAME: USDC

  - ACTIONS_USDT:
      SERVICE_NAME: microservice-solana-user-actions-usdt
      ENV_FLU_WORKER_ID: solana-devnet-microservice-solana-user-actions-usdt
      ENV_FLU_SOLANA_FLUID_MINT_PUBKEY: 97JpYk6S7i9ydzjNwb92DQEfsA1KUUWSwnWGaGDFe6bk
      ENV_FLU_SOLANA_PDA_PUBKEY: CsCAmWNMWXemyFL3QBoR3v8BU5nwGEvG5qcAKVFxzAjY
      ENV_FLU_SOLANA_TOKEN_SHORT_NAME: USDT
