SERVICES:
  - PRIZE_POOL:
      SERVICE_NAME: microservice-ethereum-prize-pool
      DOCKERFILE_PATH: ./cmd/microservice-ethereum-prize-pool
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-prize-pool
      ENV_FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR: "0x65c816077C29b557BEE980ae3cC2dCE80204A0C5"
      ENV_FLU_ETHEREUM_AAVE_ADDRESS_PROVIDER_ADDR: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
      ENV_FLU_ETHEREUM_USD_TOKEN_ADDR: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
      SECRET_FLU_ETHEREUM_TOKENS_LIST: /fluidity/ethereum/token_list
      SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ethereum/http_url
  
  - ETH_BLOCK_FLUID_TRANSERS_AMQP:
      SERVICE_NAME: microservice-ethereum-block-fluid-transfers-amqp
      DOCKERFILE_PATH: ./cmd/microservice-ethereum-block-fluid-transfers-amqp
      ENV_FLU_WORKER_ID: ethereum-staging-microservice-ethereum-block-fluid-transfers-amqp
      SECRET_FLU_ETHEREUM_WS_URL: /fluidity/ethereum/websoket_url
      SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ethereum/http_url






  