#!/bin/sh

automation_dir="$(dirname "$0")/../automation"

export \
	FLU_AMQP_QUEUE_ADDR=amqp://fluidity:fluidity@rabbitmq

export \
	FLU_SOLANA_FRONTEND_API_URL=http://localhost:8084 \
	FLU_SOLANA_FRONTEND_WS_URL=ws://localhost:8084/updates \
	FLU_SOLANA_NETWORK=devnet

export \
	FLU_SOLANA_PROGRAM_ID=GjRwsHMgCAX2QUrw64tyT9RQhqm28fmntNAjgxoaTztU \
	FLU_SOLANA_PRIZE_POOL_UPDATE_TIME=1m \
	FLU_SOLANA_TVL_DATA_PUBKEY=H2foXjvceQu7dPE8v8f3uMz83Cs3FJeYxQy65Ybgzot4 \
	FLU_SOLANA_SOLEND_PROGRAM_ID=ALend7Ketfx5bxh6ghsCDXAoDrhvEmsXT3cynB6aPLgx \
	FLU_SOLANA_STARTING_SLOT=latest

export \
	FLU_SOLANA_SABER_RPC_URL=https://saberqltest.aleph.cloud \
	FLU_SOLANA_SABER_SWAP_PROGRAM_ID=SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ \
	FLU_SOLANA_SOL_PYTH_PUBKEY=J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix

export \
	FLU_SOLANA_BASE_MINT_USDC=zVzi5VAf4qMEwzv7NXECVx5v2pQ7xnqVVjCXZwS9XzA \
	FLU_SOLANA_FLUID_MINT_PUBKEY_USDC=2XGVdHsAiMM9QDM9tV4fwQ2JnyWdSJaiXp2KifLJD1oa \
	FLU_SOLANA_PDA_PUBKEY_USDC=89B3rmx8nL7Zc2t6AhFEbC7g2bkzBZTGGdWEibLe3jBW \
	FLU_SOLANA_OBLIGATION_PUBKEY_USDC=HbmfhzwMF71jWxfKoD7sjCLrsVhvt2zEEux8t8oWqFAH \
	FLU_SOLANA_RESERVE_PUBKEY_USDC=FNNkz4RCQezSSS71rW2tvqZH1LCkTzaiG7Nd1LeA5x5y \
	FLU_SOLANA_PYTH_PUBKEY_USDC=5SSkXsEKQepHHAewytPVwdej4epN1nxgLVM84L4KXgy7 \
	FLU_SOLANA_SWITCHBOARD_PUBKEY_USDC=CZx29wKMUxaJDq6aLVQTdViPL754tTR64NAgQBUGxxHb \
	FLU_SOLANA_DATA_ACCOUNT_USDC=7ZaehFMj49vvLQbRpWhfv1evF1c8jMcuLkXy4YFAfb52 \
	FLU_SOLANA_TOKEN_SHORT_NAME_USDC=USDC \
	FLU_SOLANA_TOKEN_DECIMALS_USDC=6

export \
	FLU_SOLANA_BASE_MINT_USDT=Bp2nLuamFZndE7gztA1iPsNVhdJeg9xfKdq7KmvjpGoP \
	FLU_SOLANA_FLUID_MINT_PUBKEY_USDT=97JpYk6S7i9ydzjNwb92DQEfsA1KUUWSwnWGaGDFe6bk \
	FLU_SOLANA_PDA_PUBKEY_USDT=F8Hi4Vjgv9dnyfVnyhkFUejvUbycSoSRBUL62QkBbMgX \
	FLU_SOLANA_OBLIGATION_PUBKEY_USDT=2VmszETnb3HkvuMKYqTaPbr7zWh8jfhHut6bUQPwAdrR \
	FLU_SOLANA_RESERVE_PUBKEY_USDT=ERm3jhg8J94hxr7KmhkRvnuYbKZgNFEL4hXzBMeb1rQ8 \
	FLU_SOLANA_PYTH_PUBKEY_USDT=38xoQ4oeJCBrcVvca2cGk7iV1dAfrmTR1kmhSCJQ8Jto \
	FLU_SOLANA_SWITCHBOARD_PUBKEY_USDT=5mp8kbkTYwWWCsKSte8rURjTuyinsqBpJ9xAQsewPDD \
	FLU_SOLANA_DATA_ACCOUNT_USDT=9hKfDTt2C7Q9NDHADQpaGTuQjmotCHfvkrmjmaYonEjy \
	FLU_SOLANA_TOKEN_SHORT_NAME_USDT=USDT \
	FLU_SOLANA_TOKEN_DECIMALS_USDT=6

export \
	FLU_TRIBECA_GOVERNOR_PUBKEY=HEqN8B5mbHkifJNZjm5XDTEEjYiKjT8UvDwMvS6T3jys \
	FLU_TRIBECA_LOCKER_PUBKEY=oXvA6jMZCyuC4dLFuKtcWSdKiAiLH9n3DK2GFU8cdsq \
	FLU_TRIBECA_SMART_WALLET_PUBKEY=Hs12MkPg7CoeueAQTSXzujoBvsN7E9u37qAWsTd6qcxm \
	FLU_TRIBECA_EXEC_COUNCIL_PUBKEY=9f4P7cdb2RfiaAcSgTm4WkJdfZAv2HSXBweKXSLV7tuw \
	FLU_TRF_DATA_STORE_PROGRAM_ID=CUASGbPL3V3mwaUWBSLd44byNAkSM7CAKKDmAN4sxL6i

export \
	FLU_UTILITY_GAUGE_PROGRAM_ID=GijCvpzEK5wQjFtekuYifb8KU3xtVERFP3mFrhf8fNNV \
	FLU_SOLANA_GAUGEMEISTER_PUBKEY=2DgRESNQ1SAkoXwESFeS8c2cZL8no1yHBU1hP6ooiVeK

export \
        FLU_SOLANA_TOKENS_LIST=$FLU_SOLANA_FLUID_MINT_PUBKEY_USDC:$FLU_SOLANA_TOKEN_SHORT_NAME_USDC:$FLU_SOLANA_TOKEN_DECIMALS_USDC:$FLU_SOLANA_OBLIGATION_PUBKEY_USDC:$FLU_SOLANA_RESERVE_PUBKEY_USDC:$FLU_SOLANA_PYTH_PUBKEY_USDC:$FLU_SOLANA_SWITCHBOARD_PUBKEY_USDC,$FLU_SOLANA_FLUID_MINT_PUBKEY_USDT:$FLU_SOLANA_TOKEN_SHORT_NAME_USDT:$FLU_SOLANA_TOKEN_DECIMALS_USDT:$FLU_SOLANA_OBLIGATION_PUBKEY_USDT:$FLU_SOLANA_RESERVE_PUBKEY_USDT:$FLU_SOLANA_PYTH_PUBKEY_USDT:$FLU_SOLANA_SWITCHBOARD_PUBKEY_USDT

export \
	FLU_SOLANA_APPLICATIONS_LIST=spl:TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA,saber:${FLU_SOLANA_SABER_SWAP_PROGRAM_ID}

docker-compose \
	-f "$automation_dir/docker-compose.rabbitmq.yml" \
	-f "$automation_dir/docker-compose.infrastructure.yml" \
	-f "$automation_dir/docker-compose.database-connectors.yml" \
	-f "$automation_dir/docker-compose.solana.yml" \
	-f "$automation_dir/docker-compose.solana-transactions-user-actions.yml" \
	-f "$automation_dir/docker-compose.solana-connectors.yml" \
	-f "$automation_dir/docker-compose.solana.fluidity.money.yml" \
	-f "$automation_dir/docker-compose.solana-tribeca.yml" \
	-f "$automation_dir/docker-compose.solana-worker.yml" \
	-f "$automation_dir/docker-compose.volumes.yml" \
	$@
