#!/bin/sh

automation_dir=automation

flu_ethereum_worker_hardhat_gas_limit=8000000

export \
	FLU_AMQP_QUEUE_ADDR="$FLU_AMQP_QUEUE_ADDR" \
	FLU_UNIVERSE=production-ethereum-mainnet

export \
	FLU_SENTRY_URL="$FLU_SENTRY_URL" \
	FLU_SLACK_WEBHOOK="$FLU_SLACK_WEBHOOK"

export \
	FLU_ETHEREUM_FRONTEND_API_URL=https://app.ethereum.fluidity.money:8081 \
	FLU_ETHEREUM_FRONTEND_WS_URL=wss://app.ethereum.fluidity.money:8081/updates \
	FLU_ETHEREUM_FRONTEND_CHAIN_ID=1 \
	FLU_ETHEREUM_FRONTEND_TOKEN_FILE=mainnet-tokens.json \
	FLU_ETHEREUM_FRONTEND_GETH_URL="$FLU_ETHEREUM_FRONTEND_GETH_URL"

export \
	FLU_ETHEREUM_WS_URL="$FLU_ETHEREUM_WS_URL" \
	FLU_ETHEREUM_HTTP_URL="$FLU_ETHEREUM_HTTP_URL" \
	FLU_ETHEREUM_START_BLOCK=latest \
	FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR=0x65c816077C29b557BEE980ae3cC2dCE80204A0C5

export \
	FLU_ETHEREUM_AAVE_ADDRESS_PROVIDER_ADDR=0xb53c1a33016b2dc2ff3653530bff1848a515c8c5 \
	FLU_ETHEREUM_USD_TOKEN_ADDR=0xdac17f958d2ee523a2206206994597c13d831ec7 \
	FLU_ETHEREUM_ETH_TOKEN_ADDR=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

export \
	FLU_ETHEREUM_CONTRACT_ADDR_FUSDC=0x815451bbD6C49e43fB1b614bf405E2A69A95D3Fc \
	FLU_ETHEREUM_CONTRACT_ADDR_USDC=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48 \
	FLU_ETHEREUM_TOKEN_NAME_FUSDC=fUSDC \
	FLU_ETHEREUM_TOKEN_NAME_USDC=USDC \
	FLU_ETHEREUM_TOKEN_DECIMALS_USDC=6 \
	FLU_ETHEREUM_CTOKEN_ADDR_USDC=0x39AA39c021dfbaE8faC545936693aC917d5E7563 \
	FLU_ETHEREUM_WORKER_GAS_LIMIT_USDC=$flu_ethereum_worker_hardhat_gas_limit \
	FLU_ETHEREUM_HARDHAT_FIX_USDC=false

export \
	FLU_ETHEREUM_CONTRACT_ADDR_FUSDT=0x777B135370b35737655a3BA7ca85bD0F08502313 \
	FLU_ETHEREUM_CONTRACT_ADDR_USDT=0xdAC17F958D2ee523a2206206994597C13D831ec7 \
	FLU_ETHEREUM_TOKEN_NAME_FUSDT=fUSDT \
	FLU_ETHEREUM_TOKEN_NAME_USDT=USDT \
	FLU_ETHEREUM_TOKEN_DECIMALS_USDT=6 \
	FLU_ETHEREUM_CTOKEN_ADDR_USDT=0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9 \
	FLU_ETHEREUM_WORKER_GAS_LIMIT_USDT=$flu_ethereum_worker_hardhat_gas_limit \
	FLU_ETHEREUM_HARDHAT_FIX_USDT=false

export \
	FLU_ETHEREUM_CONTRACT_ADDR_FDAI=0xF7449745797B4A5932055aECF5c80AE504Bc1495 \
	FLU_ETHEREUM_CONTRACT_ADDR_DAI=0x6B175474E89094C44Da98b954EedeAC495271d0F \
	FLU_ETHEREUM_TOKEN_NAME_FDAI=fDAI \
	FLU_ETHEREUM_TOKEN_NAME_DAI=DAI \
	FLU_ETHEREUM_TOKEN_DECIMALS_DAI=18 \
	FLU_ETHEREUM_CTOKEN_ADDR_DAI=0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643 \
	FLU_ETHEREUM_WORKER_GAS_LIMIT_DAI=$flu_ethereum_worker_hardhat_gas_limit \
	FLU_ETHEREUM_HARDHAT_FIX_DAI=false

export \
	FLU_ETHEREUM_CONTRACT_ADDR_FTUSD=0xA49BB086ca9Fa2DFbb9feE1b2033112485b743D4 \
	FLU_ETHEREUM_CONTRACT_ADDR_TUSD=0x0000000000085d4780B73119b644AE5ecd22b376 \
	FLU_ETHEREUM_TOKEN_NAME_FTUSD=fTUSD \
	FLU_ETHEREUM_TOKEN_NAME_TUSD=TUSD \
	FLU_ETHEREUM_TOKEN_DECIMALS_TUSD=18 \
	FLU_ETHEREUM_CTOKEN_ADDR_TUSD=0x12392f67bdf24fae0af363c24ac620a2f67dad86 \
	FLU_ETHEREUM_WORKER_GAS_LIMIT_TUSD=$flu_ethereum_worker_hardhat_gas_limit \
	FLU_ETHEREUM_HARDHAT_FIX_TUSD=false

export \
	FLU_ETHEREUM_CONTRACT_ADDR_FFEI=0x3cd03e4016d3DD590AFD524daBede7609EC357CA \
	FLU_ETHEREUM_CONTRACT_ADDR_FEI=0x956F47F50A910163D8BF957Cf5846D573E7f87CA \
	FLU_ETHEREUM_TOKEN_NAME_FFEI=fFEI \
	FLU_ETHEREUM_TOKEN_NAME_FEI=FEI \
	FLU_ETHEREUM_TOKEN_DECIMALS_FEI=18 \
	FLU_ETHEREUM_ATOKEN_ADDR_FEI=0x683923dB55Fead99A79Fa01A27EeC3cB19679cC3 \
	FLU_ETHEREUM_WORKER_GAS_LIMIT_FEI=$flu_ethereum_worker_hardhat_gas_limit \
	FLU_ETHEREUM_HARDHAT_FIX_FEI=false

export \
	FLU_ETHEREUM_CONTRACT_ADDR_FFRAX=0xeDfE9eD77162e7EA830FC4aE8a892b7E4b8D4940 \
	FLU_ETHEREUM_CONTRACT_ADDR_FRAX=0x853d955aCEf822Db058eb8505911ED77F175b99e \
	FLU_ETHEREUM_TOKEN_NAME_FFRAX=fFRAX \
	FLU_ETHEREUM_TOKEN_NAME_FRAX=FRAX \
	FLU_ETHEREUM_TOKEN_DECIMALS_FRAX=18 \
	FLU_ETHEREUM_ATOKEN_ADDR_FRAX=0xd4937682df3C8aEF4FE912A96A74121C0829E664 \
	FLU_ETHEREUM_WORKER_GAS_LIMIT_FRAX=$flu_ethereum_worker_hardhat_gas_limit \
	FLU_ETHEREUM_HARDHAT_FIX_FRAX=false

export \
	FLU_ETHEREUM_CONTRACT_ADDR_FUST= \
	# FLU_ETHEREUM_CONTRACT_ADDR_UST=0xa47c8bf37f92aBed4A126BDA807A7b7498661acD \
	FLU_ETHEREUM_CONTRACT_ADDR_UST=0xa693B19d2931d498c5B318dF961919BB4aee87a5 \
	FLU_ETHEREUM_TOKEN_NAME_FUST=fUST \
	FLU_ETHEREUM_TOKEN_NAME_UST=UST \
	FLU_ETHEREUM_TOKEN_DECIMALS_UST=6 \
	FLU_ETHEREUM_ATOKEN_ADDR_UST=0xc2e2152647F4C26028482Efaf64b2Aa28779EFC4 \
	FLU_ETHEREUM_WORKER_GAS_LIMIT_UST=$flu_ethereum_worker_hardhat_gas_limit \
	FLU_ETHEREUM_HARDHAT_FIX_UST=false

export FLU_ETHEREUM_HARDHAT_FIX=false

export \
	FLU_ETHEREUM_TOKEN_BACKEND_USDC=compound \
	FLU_ETHEREUM_TOKEN_BACKEND_USDT=compound \
	FLU_ETHEREUM_TOKEN_BACKEND_DAI=compound \
	FLU_ETHEREUM_TOKEN_BACKEND_TUSD=compound \
	FLU_ETHEREUM_TOKEN_BACKEND_FEI=aave \
	FLU_ETHEREUM_TOKEN_BACKEND_FRAX=aave \
	FLU_ETHEREUM_TOKEN_BACKEND_UST=aave \

# <fluid contract>:<base token name>:<token decimals>:<underlying address>:<backend>,...
export \
	FLU_ETHEREUM_TOKENS_LIST=$FLU_ETHEREUM_CONTRACT_ADDR_FUSDT:$FLU_ETHEREUM_TOKEN_NAME_USDT:$FLU_ETHEREUM_TOKEN_DECIMALS_USDT:$FLU_ETHEREUM_CONTRACT_ADDR_USDT:$FLU_ETHEREUM_TOKEN_BACKEND_USDT,$FLU_ETHEREUM_CONTRACT_ADDR_FUSDC:$FLU_ETHEREUM_TOKEN_NAME_USDC:$FLU_ETHEREUM_TOKEN_DECIMALS_USDC:$FLU_ETHEREUM_CONTRACT_ADDR_USDC:$FLU_ETHEREUM_TOKEN_BACKEND_USDC,$FLU_ETHEREUM_CONTRACT_ADDR_FDAI:$FLU_ETHEREUM_TOKEN_NAME_DAI:$FLU_ETHEREUM_TOKEN_DECIMALS_DAI:$FLU_ETHEREUM_CONTRACT_ADDR_DAI:$FLU_ETHEREUM_TOKEN_BACKEND_DAI,$FLU_ETHEREUM_CONTRACT_ADDR_FTUSD:$FLU_ETHEREUM_TOKEN_NAME_TUSD:$FLU_ETHEREUM_TOKEN_DECIMALS_TUSD:$FLU_ETHEREUM_CONTRACT_ADDR_TUSD:$FLU_ETHEREUM_TOKEN_BACKEND_TUSD,$FLU_ETHEREUM_CONTRACT_ADDR_FFEI:$FLU_ETHEREUM_TOKEN_NAME_FEI:$FLU_ETHEREUM_TOKEN_DECIMALS_FEI:$FLU_ETHEREUM_CONTRACT_ADDR_FEI:$FLU_ETHEREUM_TOKEN_BACKEND_FEI,$FLU_ETHEREUM_CONTRACT_ADDR_FFRAX:$FLU_ETHEREUM_TOKEN_NAME_FRAX:$FLU_ETHEREUM_TOKEN_DECIMALS_FRAX:$FLU_ETHEREUM_CONTRACT_ADDR_FRAX:$FLU_ETHEREUM_TOKEN_BACKEND_FRAX,$FLU_ETHEREUM_CONTRACT_ADDR_FUST:$FLU_ETHEREUM_TOKEN_NAME_UST:$FLU_ETHEREUM_TOKEN_DECIMALS_UST:$FLU_ETHEREUM_CONTRACT_ADDR_UST:$FLU_ETHEREUM_TOKEN_BACKEND_UST

export \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDC="$FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDC" \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDT="$FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDT" \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_DAI="$FLU_ETHEREUM_WORKER_PRIVATE_KEY_DAI" \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_TUSD="$FLU_ETHEREUM_WORKER_PRIVATE_KEY_TUSD" \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_FEI="$FLU_ETHEREUM_WORKER_PRIVATE_KEY_FEI" \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_FRAX="$FLU_ETHEREUM_WORKER_PRIVATE_KEY_FRAX" \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_UST="$FLU_ETHEREUM_WORKER_PRIVATE_KEY_UST"

export \
	FLU_ETHEREUM_WORKER_HARDHAT_FIX_USDC=false \
	FLU_ETHEREUM_WORKER_HARDHAT_FIX_USDT=false \
	FLU_ETHEREUM_WORKER_HARDHAT_FIX_DAI=false \
	FLU_ETHEREUM_WORKER_HARDHAT_FIX_TUSD=false \
	FLU_ETHEREUM_WORKER_HARDHAT_FIX_FEI=false \
	FLU_ETHEREUM_WORKER_HARDHAT_FIX_FRAX=false \
	FLU_ETHEREUM_WORKER_HARDHAT_FIX_UST=false

docker-compose \
	-f "$automation_dir/docker-compose.infrastructure.yml" \
	-f "$automation_dir/docker-compose.volumes.yml" \
	-f "$automation_dir/docker-compose.database-connectors.yml" \
	-f "$automation_dir/docker-compose.ethereum.yml" \
	-f "$automation_dir/docker-compose.ethereum.fluidity.money.yml" \
	-f "$automation_dir/docker-compose.ethereum-connectors.yml" \
	-f "$automation_dir/docker-compose.ethereum-mainnet.yml" \
	-f "$automation_dir/docker-compose.ethereum-worker-mainnet.yml" \
	$@
