#!/bin/sh

automation_dir="$(dirname "$0")/../automation"

export \
	FLU_AMQP_QUEUE_ADDR=amqp://fluidity:fluidity@rabbitmq \
	FLU_UNIVERSE=testing

export \
	FLU_SOLANA_FRONTEND_API_URL=http://localhost:8084 \
	FLU_SOLANA_FRONTEND_WS_URL=ws://localhost:8084/updates

export \
	FLU_SOLANA_PROGRAM_ID=HXCKzsLf5ohVEYo5shk7MjhbqeUemwikBj4667aPhmK9 \
	FLU_SOLANA_PRIZE_POOL_UPDATE_TIME=1m \
	FLU_SOLANA_TVL_DATA_PUBKEY=H2foXjvceQu7dPE8v8f3uMz83Cs3FJeYxQy65Ybgzot4 \
	FLU_SOLANA_SOLEND_PROGRAM_ID=ALend7Ketfx5bxh6ghsCDXAoDrhvEmsXT3cynB6aPLgx \
	FLU_SOLANA_STARTING_SLOT=latest \
	FLU_SOLANA_TVL_SOLEND_PUBKEY=ALend7Ketfx5bxh6ghsCDXAoDrhvEmsXT3cynB6aPLgx

export \
	FLU_SOLANA_SABER_RPC_URL=https://saberqltest.aleph.cloud \
	FLU_SOLANA_SABER_SWAP_PROGRAM_ID=SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ \
	FLU_SOLANA_SOL_PYTH_PUBKEY=J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix

export \
	FLU_SOLANA_BASE_MINT_USDC=zVzi5VAf4qMEwzv7NXECVx5v2pQ7xnqVVjCXZwS9XzA \
	FLU_SOLANA_FLUID_MINT_PUBKEY_USDC=5jsh1taLrqNgiV3UN8diDxZAXRC7T4iALfNWwThBksoj \
	FLU_SOLANA_PDA_PUBKEY_USDC=F3bNiT1rmu1Aqt6o43miDuXh9v7M6BAqysS96Tik2NKe \
	FLU_SOLANA_OBLIGATION_PUBKEY_USDC=AzC4PyevxfhrRcY4x7Xm94PQyf9nfjcheLsSiE53Rcy \
	FLU_SOLANA_RESERVE_PUBKEY_USDC=FNNkz4RCQezSSS71rW2tvqZH1LCkTzaiG7Nd1LeA5x5y \
	FLU_SOLANA_PYTH_PUBKEY_USDC=5SSkXsEKQepHHAewytPVwdej4epN1nxgLVM84L4KXgy7 \
	FLU_SOLANA_SWITCHBOARD_PUBKEY_USDC=CZx29wKMUxaJDq6aLVQTdViPL754tTR64NAgQBUGxxHb \
	FLU_SOLANA_DATA_ACCOUNT_USDC=DDuNyoNKZMM2fSanMKUjwhtwkY5Jcg85sMoR98fsYKjU \
	FLU_SOLANA_TOKEN_SHORT_NAME_USDC=USDC \
	FLU_SOLANA_TOKEN_DECIMALS_USDC=6

export \
	FLU_SOLANA_BASE_MINT_USDT=Bp2nLuamFZndE7gztA1iPsNVhdJeg9xfKdq7KmvjpGoP \
	FLU_SOLANA_FLUID_MINT_PUBKEY_USDT=Dx8dUQ8p8zbQwv7jvXqaEdYWcK7AroNifHbcAC7YYRjg \
	FLU_SOLANA_PDA_PUBKEY_USDT=CsCAmWNMWXemyFL3QBoR3v8BU5nwGEvG5qcAKVFxzAjY \
	FLU_SOLANA_OBLIGATION_PUBKEY_USDT=EHxPXaojrnNGmUDBqz8fCbcdgYswn9MpNHtKMR6WkY7z \
	FLU_SOLANA_RESERVE_PUBKEY_USDT=ERm3jhg8J94hxr7KmhkRvnuYbKZgNFEL4hXzBMeb1rQ8 \
	FLU_SOLANA_PYTH_PUBKEY_USDT=38xoQ4oeJCBrcVvca2cGk7iV1dAfrmTR1kmhSCJQ8Jto \
	FLU_SOLANA_SWITCHBOARD_PUBKEY_USDT=5mp8kbkTYwWWCsKSte8rURjTuyinsqBpJ9xAQsewPDD \
	FLU_SOLANA_DATA_ACCOUNT_USDT=2PjRnkPxcpCZpokn45B23GLEYiwJnWgcfjXNQZ1E55ze \
	FLU_SOLANA_TOKEN_SHORT_NAME_USDT=USDT \
	FLU_SOLANA_TOKEN_DECIMALS_USDT=6

export \
    FLU_SOLANA_RPC_URL=http://api.devnet.solana.com \
    FLU_SOLANA_WS_URL=ws://api.devnet.solana.com \
    FLU_AMQP_QUEUE_ADDR=amqp://fluidity:fluidity@rabbitmq  \
    FLU_UNIVERSE=testing \
    FLU_TRIBECA_GOVERNOR_PUBKEY=5eEt6mrrP5EpKvmrUHkuahrY255vmCd4zZPvvpv2k8BD \
    FLU_TRIBECA_LOCKER_PUBKEY=6MEu1f6SvM4mTo5TTGD7ksqqU1FFuxA4z44ojQDngJtK \
    FLU_TRIBECA_SMART_WALLET_PUBKEY=Fjq8tufmjEdkwsiE2WTthNYmHPHDXPqzqfCScQr899wh \
    FLU_TRIBECA_EXEC_COUNCIL_PUBKEY=HCxVJh5f9FgeeRz198GTkq59JVgSXucJ6WwZUeQ2ut8p \
    FLU_TRIBECA_DATA_STORE_PUBKEY=2gbXEmTJy5ykGMAbavqcCwGfpwfHFa2x6GCA9NdPmv91

export \
        FLU_SOLANA_TOKENS_LIST=$FLU_SOLANA_FLUID_MINT_PUBKEY_USDC:$FLU_SOLANA_TOKEN_SHORT_NAME_USDC:$FLU_SOLANA_TOKEN_DECIMALS_USDC:$FLU_SOLANA_OBLIGATION_PUBKEY_USDC:$FLU_SOLANA_RESERVE_PUBKEY_USDC:$FLU_SOLANA_PYTH_PUBKEY_USDC:$FLU_SOLANA_SWITCHBOARD_PUBKEY_USDC,$FLU_SOLANA_FLUID_MINT_PUBKEY_USDT:$FLU_SOLANA_TOKEN_SHORT_NAME_USDT:$FLU_SOLANA_TOKEN_DECIMALS_USDT:$FLU_SOLANA_OBLIGATION_PUBKEY_USDT:$FLU_SOLANA_RESERVE_PUBKEY_USDT:$FLU_SOLANA_PYTH_PUBKEY_USDT:$FLU_SOLANA_SWITCHBOARD_PUBKEY_USDT

export FLU_SOLANA_DEBUG_FAKE_PAYOUTS=true

docker-compose \
    -f "$automation_dir/docker-compose.rabbitmq.yml" \
	-f "$automation_dir/docker-compose.infrastructure.yml" \
	-f "$automation_dir/docker-compose.database-connectors.yml" \
	-f "$automation_dir/docker-compose.solana.yml" \
	-f "$automation_dir/docker-compose.solana-connectors.yml" \
	-f "$automation_dir/docker-compose.solana-tribeca.yml" \
	-f "$automation_dir/docker-compose.volumes.yml" \
	$@
