#!/bin/sh -e

automation_dir=automation

flu_ethereum_worker_hardhat_gas_limit=8000000

export \
	FLU_AMQP_QUEUE_ADDR="$FLU_AMQP_QUEUE_ADDR" \
	FLU_UNIVERSE=production-aurora-mainnet

export \
	FLU_SENTRY_URL="$FLU_SENTRY_URL" \
	FLU_SLACK_WEBHOOK="$FLU_SLACK_WEBHOOK"

export \
	FLU_ETHEREUM_FRONTEND_API_URL=https://app.aurora.fluidity.money:8081 \
	FLU_ETHEREUM_FRONTEND_WS_URL=wss://app.aurora.fluidity.money:8081/updates \
	FLU_ETHEREUM_FRONTEND_CHAIN_ID=1313161554 \
	FLU_ETHEREUM_FRONTEND_TOKEN_FILE=aurora-mainnet-tokens.json \
	FLU_ETHEREUM_FRONTEND_GETH_URL="$FLU_ETHEREUM_FRONTEND_GETH_URL"

export \
	FLU_ETHEREUM_WS_URL="$FLU_ETHEREUM_WS_URL" \
	FLU_ETHEREUM_HTTP_URL="$FLU_ETHEREUM_HTTP_URL" \
	FLU_ETHEREUM_ORACLE_ADDRESS=0xff3eb7968d18cd94f07c94d921a93e5ce351b4e5 \
	FLU_ETHEREUM_START_BLOCK="$FLU_ETHEREUM_START_BLOCK" \
	FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR=

export \
	FLU_ETHEREUM_CONTRACT_ADDR_FUSDC=0x4E22F479677040a88b1c0282f3c9AA7d0CfEeAE3 \
	FLU_ETHEREUM_CONTRACT_ADDR_USDC=0xb12bfca5a55806aaf64e99521918a4bf0fc40802 \
	FLU_ETHEREUM_TOKEN_NAME_FUSDC=fUSDC \
	FLU_ETHEREUM_TOKEN_NAME_USDC=USDC \
	FLU_ETHEREUM_TOKEN_DECIMALS_USDC=6 \
	FLU_ETHEREUM_CTOKEN_ADDR_USDC=0xe5308dc623101508952948b141fD9eaBd3337D99 \
	FLU_AURORA_FLUX_ORACLE_USDC=0x06b35392094610C8D21FB2409855e231869B287F \
	FLU_ETHEREUM_WORKER_GAS_LIMIT_USDC=$flu_ethereum_worker_hardhat_gas_limit \
	FLU_ETHEREUM_HARDHAT_FIX_USDC=false

export \
	FLU_ETHEREUM_CONTRACT_ADDR_FUSDT=0xc0E8cD3538ba67179724f0d913907b96E6c6DDE8 \
	FLU_ETHEREUM_CONTRACT_ADDR_USDT=0x4988a896b1227218e4a686fde5eabdcabd91571f \
	FLU_ETHEREUM_TOKEN_NAME_FUSDT=fUSDT \
	FLU_ETHEREUM_TOKEN_NAME_USDT=USDT \
	FLU_ETHEREUM_TOKEN_DECIMALS_USDT=6 \
	FLU_ETHEREUM_CTOKEN_ADDR_USDT=0x845E15A441CFC1871B7AC610b0E922019BaD9826 \
	FLU_AURORA_FLUX_ORACLE_USDT=0x5c8C275Bb70C66330F5f60E17530f37a50E6185E \
	FLU_ETHEREUM_WORKER_GAS_LIMIT_USDT=$flu_ethereum_worker_hardhat_gas_limit \
	FLU_ETHEREUM_HARDHAT_FIX_USDT=true

# flux oracle
export \
	FLU_ETHEREUM_ETH_DECIMAL_PLACES=8 \
	FLU_AURORA_ETH_FLUX_ORACLE=0xA8Ac2Fa1D239c7d96046967ED21503D1F1fB2354

export FLU_ETHEREUM_HARDHAT_FIX=false

export \
	FLU_ETHEREUM_TOKENS_LIST=$FLU_ETHEREUM_CONTRACT_ADDR_FUSDT:$FLU_ETHEREUM_TOKEN_NAME_USDT:$FLU_ETHEREUM_TOKEN_DECIMALS_USDT:$FLU_AURORA_FLUX_ORACLE_USDT,$FLU_ETHEREUM_CONTRACT_ADDR_FUSDC:$FLU_ETHEREUM_TOKEN_NAME_USDC:$FLU_ETHEREUM_TOKEN_DECIMALS_USDC:$FLU_AURORA_FLUX_ORACLE_USDC

export \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDT="$FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDT" \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDC="$FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDC"

export \
	FLU_ETHEREUM_WORKER_PRIVATE_KEY_LIST="$FLU_ETHEREUM_TOKEN_NAME_USDT:$FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDT,$FLU_ETHEREUM_TOKEN_NAME_USDC:$FLU_ETHEREUM_WORKER_PRIVATE_KEY_USDC"

export \
	FLU_ETHEREUM_SPOOLER_INSTANT_REWARD_THRESHOLD=1 \
	FLU_ETHEREUM_SPOOLER_TOTAL_REWARD_THRESHOLD=1

export \
	FLU_ETHEREUM_WORKER_HARDHAT_FIX_USDC=false \
	FLU_ETHEREUM_WORKER_HARDHAT_FIX_USDT=false

docker-compose \
	-f "$automation_dir/docker-compose.volumes.yml" \
	-f "$automation_dir/docker-compose.infrastructure.yml" \
	-f "$automation_dir/docker-compose.database-connectors.yml" \
	-f "$automation_dir/docker-compose.ethereum.yml" \
	-f "$automation_dir/docker-compose.ethereum.fluidity.money.yml" \
	-f "$automation_dir/docker-compose.ethereum-connectors.yml" \
	-f "$automation_dir/docker-compose.aurora-mainnet.yml" \
	-f "$automation_dir/docker-compose.aurora-worker.yml" \
	$@
