#!/bin/sh

automation_dir="$(dirname "$0")/../automation"

export FLU_UNIVERSE=mainnet-solana

export \
	FLU_SOLANA_PROGRAM_ID=HEvunKKgzf4SMZimVMET6HuzAyfGJS4ZMShUz94KLUdR \
	FLU_SOLANA_PRIZE_POOL_UPDATE_TIME=1m \
	FLU_SOLANA_TVL_DATA_PUBKEY=B6xiDeQ9gNHdM4XG1VqHwyFR3AqUukKAzzhDFJirkgqP \
	FLU_SOLANA_SOLEND_PROGRAM_ID= \
	FLU_SOLANA_STARTING_SLOT=latest \
	FLU_SOLANA_TVL_SOLEND_PUBKEY=So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo

export \
	FLU_SOLANA_SABER_RPC_URL=https://saberqltest.aleph.cloud \
	FLU_SOLANA_SABER_SWAP_PROGRAM_ID=SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ \
	FLU_SOLANA_SOL_PYTH_PUBKEY=H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG

export \
	FLU_SOLANA_BASE_MINT_USDC=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v \
	FLU_SOLANA_FLUID_MINT_PUBKEY_USDC=Ez2zVjw85tZan1ycnJ5PywNNxR6Gm4jbXQtZKyQNu3Lv \
	FLU_SOLANA_PDA_PUBKEY_USDC=CBrYRFyEwyn9gMPVFbRBwfcoU6JnViTEBaYyvFZGgZnc \
	FLU_SOLANA_OBLIGATION_PUBKEY_USDC=J6ZHkcCiAKSKTmoUZzozZ2L1Wwm34WF2VQamyu2Sno6A \
	FLU_SOLANA_RESERVE_PUBKEY_USDC=UZXSyWf2azJMKaoG5trn5AJHBLWtZYC5DNTdp1WW9Ki \
	FLU_SOLANA_PYTH_PUBKEY_USDC=Gnt27xtC473ZT2Mw5u8wZ68Z3gULkSTb5DuxJy7eJotD \
	FLU_SOLANA_SWITCHBOARD_PUBKEY_USDC=CZx29wKMUxaJDq6aLVQTdViPL754tTR64NAgQBUGxxHb \
	FLU_SOLANA_DATA_ACCOUNT_USDC=nZtk79qJyUXMg53SYL9wZQnMUjwJeTFGTfKmFaEehKq \
	FLU_SOLANA_TOKEN_SHORT_NAME_USDC=USDC \
	FLU_SOLANA_TOKEN_DECIMALS_USDC=6

export \
	FLU_SOLANA_BASE_MINT_USDT=Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB \
	FLU_SOLANA_FLUID_MINT_PUBKEY_USDT=D5zHHS5tkf9zfGBRPQbDKpUiRAMVK8VvxGwTHP6tP1B8 \
	FLU_SOLANA_PDA_PUBKEY_USDT=5tCSTEkozvUw9YZxZzsGkR9upMQNacFEBiYN21nfCj77 \
	FLU_SOLANA_OBLIGATION_PUBKEY_USDT=446FsyYfANPuiK18DYGLwQm6B5b2MecTUvm1KtnDMGca \
	FLU_SOLANA_RESERVE_PUBKEY_USDT=9qmqAixDzfMzYjqdSbxz7wY7Vgr2yxBtPqLuA3PE9xCh \
	FLU_SOLANA_PYTH_PUBKEY_USDT=3vxLXJqLqF3JG5TCbYycbKWRBbCJQLxQmBGCkyqEEefL \
	FLU_SOLANA_SWITCHBOARD_PUBKEY_USDT=5mp8kbkTYwWWCsKSte8rURjTuyinsqBpJ9xAQsewPDD \
	FLU_SOLANA_DATA_ACCOUNT_USDT=C8csqsv1NxAC2ge1ZAvToaHZa8VsffmxewHHYJ7JuDVD \
	FLU_SOLANA_TOKEN_SHORT_NAME_USDT=USDT \
	FLU_SOLANA_TOKEN_DECIMALS_USDT=6

export \
        FLU_SOLANA_TOKENS_LIST=$FLU_SOLANA_FLUID_MINT_PUBKEY_USDC:$FLU_SOLANA_TOKEN_SHORT_NAME_USDC:$FLU_SOLANA_TOKEN_DECIMALS_USDC:$FLU_SOLANA_OBLIGATION_PUBKEY_USDC:$FLU_SOLANA_RESERVE_PUBKEY_USDC:$FLU_SOLANA_PYTH_PUBKEY_USDC:$FLU_SOLANA_SWITCHBOARD_PUBKEY_USDC,$FLU_SOLANA_FLUID_MINT_PUBKEY_USDT:$FLU_SOLANA_TOKEN_SHORT_NAME_USDT:$FLU_SOLANA_TOKEN_DECIMALS_USDT:$FLU_SOLANA_OBLIGATION_PUBKEY_USDT:$FLU_SOLANA_RESERVE_PUBKEY_USDT:$FLU_SOLANA_PYTH_PUBKEY_USDT:$FLU_SOLANA_SWITCHBOARD_PUBKEY_USDT

export FLU_SOLANA_DEBUG_FAKE_PAYOUTS=false

docker-compose \
	-f "$automation_dir/docker-compose.infrastructure.yml" \
	-f "$automation_dir/docker-compose.database-connectors.yml" \
	-f "$automation_dir/docker-compose.solana.yml" \
	-f "$automation_dir/docker-compose.solana-transactions-user-actions.yml" \
	-f "$automation_dir/docker-compose.solana-connectors.yml" \
	-f "$automation_dir/docker-compose.solana.fluidity.money.yml" \
	-f "$automation_dir/docker-compose.solana-worker.yml" \
	-f "$automation_dir/docker-compose.volumes.yml" \
	$@
