#!/bin/sh

AUTOMATION_DIR=automation

export \
	FLU_ETHEREUM_WS_URL=ws://contracts-ethereum:8545 \
	FLU_ETHEREUM_HTTP_URL=http://contracts-ethereum:8545 \
	FLU_ETHEREUM_ORACLE_ADDRESS=0x50Ab74ed0dac2f82924D6E748Ce22eBeE339184c \
	FLU_ETHEREUM_START_BLOCK=latest \
	FLU_ETHEREUM_UNISWAP_ANCHORED_VIEW_ADDR=0x6d2299c48a8dd07a872fdd0f8233924872ad1071

export \
	FLU_ETHEREUM_CONTRACT_ADDR_DAI=0xddd63f96e78dced5b6ef17ee285f2cdbdf8972ab \
	FLU_ETHEREUM_TOKEN_NAME_DAI=DAI \
	FLU_ETHEREUM_TOKEN_DECIMALS_DAI=18 \

export \
	FLU_ETHEREUM_CONTRACT_ADDR_USDC=0x737f9dc58538b222a6159efa9cc548ab4b7a3f1e \
	FLU_ETHEREUM_TOKEN_NAME_USDC=USDC \
	FLU_ETHEREUM_TOKEN_DECIMALS_USDC=6 \

export \
	FLU_ETHEREUM_CONTRACT_ADDR_USDT=0x9391202b846ee3f574e59e4ad58ef6140e9ba4f6 \
	FLU_ETHEREUM_TOKEN_NAME_USDT=USDT \
	FLU_ETHEREUM_TOKEN_DECIMALS_USDT=6

export \
	FLU_ETHEREUM_TOKENS_LIST=$FLU_ETHEREUM_CONTRACT_ADDR_USDT:$FLU_ETHEREUM_TOKEN_NAME_USDT:$FLU_ETHEREUM_TOKEN_DECIMALS_USDT,$FLU_ETHEREUM_CONTRACT_ADDR_USDC:$FLU_ETHEREUM_TOKEN_NAME_USDC:$FLU_ETHEREUM_TOKEN_DECIMALS_USDT,$FLU_ETHEREUM_CONTRACT_ADDR_DAI:$FLU_ETHEREUM_TOKEN_NAME_DAI:$FLU_ETHEREUM_TOKEN_DECIMALS_DAI

export \
	FLU_ETHEREUM_FRONTEND_API_URL=http://localhost:8081 \
	FLU_ETHEREUM_FRONTEND_WS_URL=ws://localhost:8081/updates \
	FLU_ETHEREUM_FRONTEND_CHAIN_ID=31337 \
	FLU_ETHEREUM_FRONTEND_TOKEN_FILE=testing-tokens.json \
	FLU_ETHEREUM_FRONTEND_GETH_URL=http://localhost:8545

export \
	FLU_FAUCET_FRONTEND_API_URL=http://localhost:8083

docker-compose \
	-f "$AUTOMATION_DIR/docker-compose.infrastructure.yml" \
	-f "$AUTOMATION_DIR/docker-compose.database-connectors.yml" \
	-f "$AUTOMATION_DIR/docker-compose.ethereum.yml" \
	-f "$AUTOMATION_DIR/docker-compose.ethereum.fluidity.money.yml" \
	-f "$AUTOMATION_DIR/docker-compose.ethereum-contracts.yml" \
	-f "$AUTOMATION_DIR/docker-compose.ethereum-connectors.yml" \
	-f "$AUTOMATION_DIR/docker-compose.faucet.fluidity.money.yml" \
	$@
