DOCKER_IMAGE: microservice-solana-application-server
DOCKERFILE_PATH: ./cmd/microservice-solana-application-server
SECRET_FLU_SOLANA_RPC_URL: /fluidity/solana/rpc_url
SECRET_FLU_SOLANA_SABER_RPC_URL: /fluidity/devnet/saber_rpc_url
ENV_FLU_SOLANA_SABER_SWAP_PROGRAM_ID: saber:SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ
ENV_FLU_SOLANA_ORCA_PROGRAM_ID: 9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP
ENV_FLU_SOLANA_RAYDIUM_PROGRAM_ID: "XXXXXX"
ENV_FLU_SOLANA_TOKEN_LOOKUPS: "fUSDT:USDT,fUSDC:USDC"

SERVICES:
  - APPSERVER:
      SERVICE_NAME: microservice-solana-application-server
      ENV_FLU_WORKER_ID: solana-devnet-microservice-solana-application-server
