SERVICES:
  - COMMON_RABBITMQ_BACKLOG_CHECKER:
      SERVICE_NAME: microservice-common-rabbitmq-backlog-checker-solana
      DOCKER_IMAGE: microservice-common-rabbitmq-backlog-checker
      DOCKERFILE_PATH: ./cmd/microservice-common-rabbitmq-backlog-checker
      DEPLOYMENT_TYPE: CRON
      
      ENV_FLU_WORKER_ID: solana-devnet-microservice-common-rabbitmq-backlog-checker
      SECRET_FLU_DISCORD_WEBHOOK: /fluidity/discord/webhook

      EVENT_ROLE: ecsEventsRole
      EVENT_RULE: microservice-common-rabbitmq-backlog-checker-solana-cron
      EVENT_SCHEDULE: rate(1 hour) #every 1hr
      
