FROM fluidity/build-container:latest AS build

WORKDIR /usr/local/src/fluidity/web/ethereum.fluidity.money

COPY . .

RUN make backend

FROM fluidity/runtime-container:latest

COPY --from=build /usr/local/src/fluidity/web/ethereum.fluidity.money/ethereum.fluidity.money.out .

ENTRYPOINT [ \
	"wait-for-amqp", \
	"wait-for-database.sh", \
	"./ethereum.fluidity.money.out" \
]
