
FROM fluidity/web-container:latest

ARG REACT_APP_API_URL
ARG REACT_APP_WALLET_CONNECT_GETH_URI
ARG REACT_APP_WEBSOCKET
ARG REACT_APP_CHAIN_ID

WORKDIR /usr/local/src/fluidity/web/ethereum.fluidity.money

ENV PRODUCTION ${PRODUCTION}

ENV PATH /app/node_modules.bin:$PATH

COPY package.json package-lock.json ./

RUN npm i

COPY . ./

RUN ls -l1

RUN pwd

RUN make frontend

RUN cp -r build /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
