

SERVICES:
  - FAUCET_BACKEND:
      SERVICE_NAME: faucet-fluidity-money-backend
      DOCKERFILE_PATH: ./web/faucet.fluidity.money
      DOCKER_IMAGE: faucet.fluidity.money-backend
      TARGET_GROUP: flu-dev-faucet-be-tg
      ENV_FLU_WORKER_ID: ethereum-ropsten-faucet.fluidity.money-backend
      SECRET_FLU_DISCORD_WEBHOOK: /fluidity/discord/webhook

  - FLUIDITY_FRONTEND:
      SERVICE_NAME: faucet-fluidity-money-frontend
      DOCKERFILE_PATH: ./web/faucet.fluidity.money
      DOCKER_IMAGE: faucet.fluidity.money-frontend
      TARGET_GROUP: flu-dev-faucet-fe-tg
      DOCKER_ARGS:
        REACT_APP_FLU_API_URI: https://faucet.fluidity.money:8081
        PRODUCTION: "true"

  - FAUCET_TRACK_TWEETS:
      SERVICE_NAME: microservice-common-faucet-track-tweets
      DOCKERFILE_PATH: ./cmd/microservice-common-faucet-track-tweets
      ENV_FLU_WORKER_ID: ethereum-ropsten-microservice-common-faucet-track-tweets
      ENV_FLU_TWITTER_HASHTAGS: fluiditymoney
      SECRET_FLU_DISCORD_WEBHOOK: /fluidity/discord/webhook

  - ETH_FAUCET_SEND_AMOUNTS:
      SERVICE_NAME: microservice-ethereum-faucet-send-amounts
      DOCKERFILE_PATH: ./cmd/microservice-ethereum-faucet-send-amounts
      ENV_FLU_WORKER_ID: ethereum-ropsten-microservice-ethereum-faucet-send-amounts
      ENV_FLU_ETHEREUM_HARDHAT_FIX: "false"
      SECRET_FLU_DISCORD_WEBHOOK: /fluidity/discord/webhook
      SECRET_FLU_ETHEREUM_TOKENS_LIST: /fluidity/ropsten/token_list
      SECRET_FLU_ETHEREUM_HTTP_URL: /fluidity/ropsten/http_url
      SECRET_FLU_ETHEREUM_FAUCET_PRIVATE_KEY: /fluidity/faucet/private_key
      TASK_MIN_COUNT: 1
      
  - SOL_FAUCET_SEND_AMOUNTS:
      SERVICE_NAME: microservice-solana-faucet-send-amounts
      DOCKERFILE_PATH: ./cmd/microservice-solana-faucet-send-amounts
      ENV_FLU_WORKER_ID: ethereum-ropsten-microservice-solana-faucet-send-amounts
      SECRET_FLU_SOLANA_RPC_URL: /fluidity/solana/rpc_url
      SECRET_FLU_SOLANA_TOKENS_LIST: /fluidity/solana/token_list
      SECRET_FLU_SOLANA_FAUCET_ACCOUNT_DETAILS: /fluidity/faucet/solana/account_details
  
  - TWITTER_HASHTAG_AMQP:
      SERVICE_NAME: connector-common-twitter-hashtag-amqp
      DOCKERFILE_PATH: ./cmd/connector-common-twitter-hashtag-amqp
      ENV_FLU_WORKER_ID: ethereum-ropsten-connector-common-twitter-hashtag-amqp
      SECRET_FLU_TWITTER_BEARER_TOKEN: /fluidity/faucet/twitter_bearer_token
      ENV_FLU_TWITTER_HASHTAGS: fluiditymoney
      TASK_MIN_COUNT: 1
