---
version: "3"

services:
  microservice-common-rabbitmq-backlog-checker:
    build:
      context: ../cmd/microservice-common-rabbitmq-backlog-checker
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-microservice-common-rabbitmq-backlog-checker
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_AMQP_USER: ${FLU_AMQP_USER}
      FLU_AMQP_USER_PASS: ${FLU_AMQP_USER_PASS}
      FLU_SLACK_WEBHOOK: ${FLU_SLACK_WEBHOOK_QUEUE_OVERLOADED}
    depends_on:
      - redis
