---
version: "3"

services:
  microservice-solana-worker-server-usdc:
    build:
      context: ../cmd/microservice-solana-worker-server
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-worker-solana-server-usdc
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_NETWORK: ${FLU_SOLANA_NETWORK}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_USDC}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_USDC}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_USDC}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_USDC}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_USDC}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_USDC}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_USDC}
      FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.usdc.winners
    depends_on:
      - redis
    restart: unless-stopped

  microservice-solana-worker-server-usdt:
    build:
      context: ../cmd/microservice-solana-worker-server
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-worker-solana-server-usdt
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_USDT}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_USDT}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_USDT}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_USDT}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_USDT}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_USDT}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_USDT}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_SOLANA_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.usdt.winners
    depends_on:
      - redis
    restart: unless-stopped

  microservice-solana-worker-server-uxd:
    build:
      context: ../cmd/microservice-solana-worker-server
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-worker-solana-server-uxd
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_UXD}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_UXD}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_UXD}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_UXD}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_UXD}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_UXD}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_UXD}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_SOLANA_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.uxd.winners
    depends_on:
      - redis
    restart: unless-stopped

  microservice-solana-worker-server-ust:
    build:
      context: ../cmd/microservice-solana-worker-server
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-worker-solana-server-ust
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_UST}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_UST}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_UST}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_UST}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_UST}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_UST}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_UST}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_SOLANA_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.ust.winners
    depends_on:
      - redis
    restart: unless-stopped

  microservice-solana-worker-client-usdc:
    build:
      context: ../cmd/microservice-solana-worker-client
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-worker-solana-client-usdc
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_USDC}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_USDC}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_USDC}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_USDC}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_USDC}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_USDC}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_USDC}
      FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.usdc.winners
    depends_on:
      - redis
    restart: unless-stopped

  microservice-solana-worker-client-usdt:
    build:
      context: ../cmd/microservice-solana-worker-client
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-worker-solana-client-usdt
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_USDT}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_USDT}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_USDT}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_USDT}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_USDT}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_USDT}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_USDT}
      FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.usdt.winners
    depends_on:
      - redis
    restart: unless-stopped

  microservice-solana-worker-client-uxd:
    build:
      context: ../cmd/microservice-solana-worker-client
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-worker-solana-client-uxd
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_UXD}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_UXD}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_UXD}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_UXD}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_UXD}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_UXD}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_UXD}
      FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.uxd.winners
    depends_on:
      - redis
    restart: unless-stopped

  microservice-solana-worker-client-ust:
    build:
      context: ../cmd/microservice-solana-worker-client
    env_file: ./docker-compose-envs
    environment:
      FLU_WORKER_ID: ${FLU_UNIVERSE}-worker-solana-client-ust
      FLU_SENTRY_URL: ${FLU_SENTRY_URL}
      FLU_AMQP_QUEUE_ADDR: ${FLU_AMQP_QUEUE_ADDR}
      FLU_SOLANA_RPC_URL: ${FLU_SOLANA_RPC_URL}
      FLU_SOLANA_PROGRAM_ID: ${FLU_SOLANA_PROGRAM_ID}
      FLU_SOLANA_FLUID_MINT_PUBKEY: ${FLU_SOLANA_FLUID_MINT_PUBKEY_UST}
      FLU_SOLANA_TVL_DATA_PUBKEY: ${FLU_SOLANA_TVL_DATA_PUBKEY}
      FLU_SOLANA_SOLEND_PROGRAM_ID: ${FLU_SOLANA_SOLEND_PROGRAM_ID}
      FLU_SOLANA_OBLIGATION_PUBKEY: ${FLU_SOLANA_OBLIGATION_PUBKEY_UST}
      FLU_SOLANA_RESERVE_PUBKEY: ${FLU_SOLANA_RESERVE_PUBKEY_UST}
      FLU_SOLANA_PYTH_PUBKEY: ${FLU_SOLANA_PYTH_PUBKEY_UST}
      FLU_SOLANA_SWITCHBOARD_PUBKEY: ${FLU_SOLANA_SWITCHBOARD_PUBKEY_UST}
      FLU_SOLANA_PAYER_PRIKEY: ${FLU_SOLANA_WORKER_PRIVATE_KEY}
      FLU_DEBUG_FAKE_PAYOUTS: ${FLU_DEBUG_FAKE_PAYOUTS}
      FLU_SOLANA_TOKEN_DECIMALS: ${FLU_SOLANA_TOKEN_DECIMALS_UST}
      FLU_SOLANA_TOKEN_NAME: ${FLU_SOLANA_TOKEN_SHORT_NAME_UST}
      FLU_SOLANA_WINNER_QUEUE_NAME: worker.solana.ust.winners
    depends_on:
      - redis
    restart: unless-stopped
