export type Provider =
  | "Aave"
  | "Aldrin"
  | "Circle"
  | "Compound"
  | "Dodo"
  | "Jupiter"
  | "Lemniscap"
  | "Maker"
  | "Multicoin"
  | "Orca"
  | "Polygon"
  | "Saber"
  | "Solana"
  | "Solend"
  | "Uniswap"
  | "Sushiswap"
  | "Fluidity"
  | "Balancer"
  | "Oneinch"
  | "Mooniswap"
  | "Curve"
  | "Multichain"
  | "XY Finance"
  | "Raydium"
  | "Lifinity"
  | "Mercurial";