---

version: "2"

services:
  postgres:
    image: fluidity/database-postgres
    environment:
      - POSTGRES_USER=fluidity
      - POSTGRES_PASSWORD=fluidity
    ports:
      - 5432:5432

  backend:
    image: fluidity/fluidity.money-backend
    environment:
      - FLU_WORKER_ID=fluidity.money
      - FLU_WEB_LISTEN_ADDR=:80
      - FLU_POSTGRES_URI=postgres://fluidity:fluidity@postgres?sslmode=disable
      - FLU_DISCORD_WEBHOOK=${FLU_DISCORD_WEBHOOK}

  frontend:
    image: fluidity/fluidity.money-frontend

  proxy:
    image: fluidity/api-proxy-docker:latest
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
