
FROM fluidity/build-web-container:latest AS build

WORKDIR /usr/local/src/fluidity/web

ENV PRODUCTION ${PRODUCTION}

ARG CI

ARG GITHUB_TOKEN

ENV CI $CI

ENV PATH /app/node_modules.bin:$PATH

COPY . ./

RUN yarn

# https://github.com/vercel/next.js/discussions/57066
RUN npm run build
RUN npm cache clean --force
RUN npm install next@latest

ARG FLU_SENTRY_DSN

WORKDIR /usr/local/src/fluidity/web/leaderboard

RUN make frontend

FROM fluidity/runtime-web-container:latest

WORKDIR /usr/local/src/fluidity/web

COPY --from=build /usr/local/src/fluidity/web .

WORKDIR /usr/local/src/fluidity/web/leaderboard

EXPOSE 3000

CMD ["yarn", "start"]
