# action.yml
name: 'fluidity-cli'
author: 'renz@fludity.money'
description: 'Build and Deploy fluidity microservices'
inputs:
  command:
    description: 'flu cli command'
    required: true
runs:
  using: 'docker'
  image: 'docker.io/flualex/flu-cli'
  args:
    - ${{ inputs.command }}