// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package locked_voter

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ActivateProposal is the `activateProposal` instruction.
type ActivateProposal struct {

	// [0] = [] locker
	//
	// [1] = [] governor
	//
	// [2] = [WRITE] proposal
	//
	// [3] = [] escrow
	//
	// [4] = [SIGNER] escrowOwner
	//
	// [5] = [] governProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewActivateProposalInstructionBuilder creates a new `ActivateProposal` instruction builder.
func NewActivateProposalInstructionBuilder() *ActivateProposal {
	nd := &ActivateProposal{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetLockerAccount sets the "locker" account.
func (inst *ActivateProposal) SetLockerAccount(locker ag_solanago.PublicKey) *ActivateProposal {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(locker)
	return inst
}

// GetLockerAccount gets the "locker" account.
func (inst *ActivateProposal) GetLockerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetGovernorAccount sets the "governor" account.
func (inst *ActivateProposal) SetGovernorAccount(governor ag_solanago.PublicKey) *ActivateProposal {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(governor)
	return inst
}

// GetGovernorAccount gets the "governor" account.
func (inst *ActivateProposal) GetGovernorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetProposalAccount sets the "proposal" account.
func (inst *ActivateProposal) SetProposalAccount(proposal ag_solanago.PublicKey) *ActivateProposal {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(proposal).WRITE()
	return inst
}

// GetProposalAccount gets the "proposal" account.
func (inst *ActivateProposal) GetProposalAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *ActivateProposal) SetEscrowAccount(escrow ag_solanago.PublicKey) *ActivateProposal {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(escrow)
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *ActivateProposal) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetEscrowOwnerAccount sets the "escrowOwner" account.
func (inst *ActivateProposal) SetEscrowOwnerAccount(escrowOwner ag_solanago.PublicKey) *ActivateProposal {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(escrowOwner).SIGNER()
	return inst
}

// GetEscrowOwnerAccount gets the "escrowOwner" account.
func (inst *ActivateProposal) GetEscrowOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetGovernProgramAccount sets the "governProgram" account.
func (inst *ActivateProposal) SetGovernProgramAccount(governProgram ag_solanago.PublicKey) *ActivateProposal {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(governProgram)
	return inst
}

// GetGovernProgramAccount gets the "governProgram" account.
func (inst *ActivateProposal) GetGovernProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst ActivateProposal) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ActivateProposal,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ActivateProposal) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ActivateProposal) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Locker is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Governor is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Proposal is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.EscrowOwner is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.GovernProgram is not set")
		}
	}
	return nil
}

func (inst *ActivateProposal) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ActivateProposal")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("       locker", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     governor", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("     proposal", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("       escrow", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("  escrowOwner", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("governProgram", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj ActivateProposal) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *ActivateProposal) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewActivateProposalInstruction declares a new ActivateProposal instruction with the provided parameters and accounts.
func NewActivateProposalInstruction(
	// Accounts:
	locker ag_solanago.PublicKey,
	governor ag_solanago.PublicKey,
	proposal ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	escrowOwner ag_solanago.PublicKey,
	governProgram ag_solanago.PublicKey) *ActivateProposal {
	return NewActivateProposalInstructionBuilder().
		SetLockerAccount(locker).
		SetGovernorAccount(governor).
		SetProposalAccount(proposal).
		SetEscrowAccount(escrow).
		SetEscrowOwnerAccount(escrowOwner).
		SetGovernProgramAccount(governProgram)
}
