// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package locked_voter

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// NewEscrow is the `newEscrow` instruction.
type NewEscrow struct {
	Bump *uint8

	// [0] = [] locker
	//
	// [1] = [WRITE] escrow
	//
	// [2] = [] escrowOwner
	//
	// [3] = [WRITE, SIGNER] payer
	//
	// [4] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewNewEscrowInstructionBuilder creates a new `NewEscrow` instruction builder.
func NewNewEscrowInstructionBuilder() *NewEscrow {
	nd := &NewEscrow{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 5),
	}
	return nd
}

// SetBump sets the "bump" parameter.
func (inst *NewEscrow) SetBump(bump uint8) *NewEscrow {
	inst.Bump = &bump
	return inst
}

// SetLockerAccount sets the "locker" account.
func (inst *NewEscrow) SetLockerAccount(locker ag_solanago.PublicKey) *NewEscrow {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(locker)
	return inst
}

// GetLockerAccount gets the "locker" account.
func (inst *NewEscrow) GetLockerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetEscrowAccount sets the "escrow" account.
func (inst *NewEscrow) SetEscrowAccount(escrow ag_solanago.PublicKey) *NewEscrow {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(escrow).WRITE()
	return inst
}

// GetEscrowAccount gets the "escrow" account.
func (inst *NewEscrow) GetEscrowAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetEscrowOwnerAccount sets the "escrowOwner" account.
func (inst *NewEscrow) SetEscrowOwnerAccount(escrowOwner ag_solanago.PublicKey) *NewEscrow {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(escrowOwner)
	return inst
}

// GetEscrowOwnerAccount gets the "escrowOwner" account.
func (inst *NewEscrow) GetEscrowOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPayerAccount sets the "payer" account.
func (inst *NewEscrow) SetPayerAccount(payer ag_solanago.PublicKey) *NewEscrow {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *NewEscrow) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *NewEscrow) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *NewEscrow {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *NewEscrow) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

func (inst NewEscrow) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_NewEscrow,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst NewEscrow) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *NewEscrow) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Bump == nil {
			return errors.New("Bump parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Locker is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Escrow is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.EscrowOwner is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *NewEscrow) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("NewEscrow")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Bump", *inst.Bump))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=5]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("       locker", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       escrow", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("  escrowOwner", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("        payer", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(4)))
					})
				})
		})
}

func (obj NewEscrow) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	return nil
}
func (obj *NewEscrow) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	return nil
}

// NewNewEscrowInstruction declares a new NewEscrow instruction with the provided parameters and accounts.
func NewNewEscrowInstruction(
	// Parameters:
	bump uint8,
	// Accounts:
	locker ag_solanago.PublicKey,
	escrow ag_solanago.PublicKey,
	escrowOwner ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *NewEscrow {
	return NewNewEscrowInstructionBuilder().
		SetBump(bump).
		SetLockerAccount(locker).
		SetEscrowAccount(escrow).
		SetEscrowOwnerAccount(escrowOwner).
		SetPayerAccount(payer).
		SetSystemProgramAccount(systemProgram)
}
