// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package locked_voter

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetLockerParams is the `setLockerParams` instruction.
type SetLockerParams struct {
	Params *LockerParams

	// [0] = [WRITE] locker
	//
	// [1] = [] governor
	//
	// [2] = [SIGNER] smartWallet
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetLockerParamsInstructionBuilder creates a new `SetLockerParams` instruction builder.
func NewSetLockerParamsInstructionBuilder() *SetLockerParams {
	nd := &SetLockerParams{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *SetLockerParams) SetParams(params LockerParams) *SetLockerParams {
	inst.Params = &params
	return inst
}

// SetLockerAccount sets the "locker" account.
func (inst *SetLockerParams) SetLockerAccount(locker ag_solanago.PublicKey) *SetLockerParams {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(locker).WRITE()
	return inst
}

// GetLockerAccount gets the "locker" account.
func (inst *SetLockerParams) GetLockerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetGovernorAccount sets the "governor" account.
func (inst *SetLockerParams) SetGovernorAccount(governor ag_solanago.PublicKey) *SetLockerParams {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(governor)
	return inst
}

// GetGovernorAccount gets the "governor" account.
func (inst *SetLockerParams) GetGovernorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSmartWalletAccount sets the "smartWallet" account.
func (inst *SetLockerParams) SetSmartWalletAccount(smartWallet ag_solanago.PublicKey) *SetLockerParams {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(smartWallet).SIGNER()
	return inst
}

// GetSmartWalletAccount gets the "smartWallet" account.
func (inst *SetLockerParams) GetSmartWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst SetLockerParams) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetLockerParams,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetLockerParams) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetLockerParams) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Locker is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Governor is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.SmartWallet is not set")
		}
	}
	return nil
}

func (inst *SetLockerParams) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetLockerParams")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     locker", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   governor", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("smartWallet", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj SetLockerParams) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetLockerParams) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewSetLockerParamsInstruction declares a new SetLockerParams instruction with the provided parameters and accounts.
func NewSetLockerParamsInstruction(
	// Parameters:
	params LockerParams,
	// Accounts:
	locker ag_solanago.PublicKey,
	governor ag_solanago.PublicKey,
	smartWallet ag_solanago.PublicKey) *SetLockerParams {
	return NewSetLockerParamsInstructionBuilder().
		SetParams(params).
		SetLockerAccount(locker).
		SetGovernorAccount(governor).
		SetSmartWalletAccount(smartWallet)
}
