SERVICES:
  - FRONTEND:
      SERVICE_NAME: fluidity-money
      DOCKER_IMAGE: fluidity.money-frontend
      DOCKERFILE_PATH: ./web/fluidity.money
      TARGET_GROUP: flu-dev-fluidity-fe-tg
      SECRET_FLU_HASURA_KEY: /fluidity/hasura/key
      SECRET_FLU_ETH_RPC_HTTP: /fluidity/ethereum/http_url
      CPU_LIMIT: 512
      MEM_LIMIT: 1024

      DOCKER_ARGS:
        SECRET_REACT_APP_SENTRY_DSN: /fluidity/frontend/sentryURL
        SECRET_GITHUB_TOKEN: /fluidity/npm/github_token


