
FROM fluidity/web-container:latest

WORKDIR /usr/local/src/fluidity/web/solana.fluidity.money

RUN make backend

ENTRYPOINT [ \
	"wait-for-amqp", \
	"wait-for-database.sh", \
	"./solana.fluidity.money.o" \
]
