export \
	REACT_APP_API_URL=https://app.solana.beta.fluidity.money:8081 \
	REACT_APP_WEBSOCKET=wss://app.solana.beta.fluidity.money:8081/updates	
        
export \
	REACT_APP_FLUID_PROGRAM_ID=HXCKzsLf5ohVEYo5shk7MjhbqeUemwikBj4667aPhmK9 \
	REACT_APP_FLU_MINT_USDC=5jsh1taLrqNgiV3UN8diDxZAXRC7T4iALfNWwThBksoj \
        REACT_APP_FLU_OBLIGATION_USDC=AzC4PyevxfhrRcY4x7Xm94PQyf9nfjcheLsSiE53Rcy \
        REACT_APP_FLU_DATA_ACCOUNT_USDC=DDuNyoNKZMM2fSanMKUjwhtwkY5Jcg85sMoR98fsYKjU \
        REACT_APP_BASE_MINT_USDC=zVzi5VAf4qMEwzv7NXECVx5v2pQ7xnqVVjCXZwS9XzA \
        REACT_APP_FLU_MINT_USDT=Dx8dUQ8p8zbQwv7jvXqaEdYWcK7AroNifHbcAC7YYRjg \
        REACT_APP_FLU_OBLIGATION_USDT=EHxPXaojrnNGmUDBqz8fCbcdgYswn9MpNHtKMR6WkY7z \
        REACT_APP_FLU_DATA_ACCOUNT_USDT=2PjRnkPxcpCZpokn45B23GLEYiwJnWgcfjXNQZ1E55ze \
        REACT_APP_BASE_MINT_USDT=Bp2nLuamFZndE7gztA1iPsNVhdJeg9xfKdq7KmvjpGoP