name: Staging (Auto Test)

on:
  push:
    branches:
      - develop-ci-slack-notif

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - name: Get Diff
        id: diff
        uses: ./scripts/actions
        with:
          command: |
            flu get-diff --environment dev --tag $GITHUB_SHA
      - name: Build
        id: build
        uses: ./scripts/actions
        with:
          command: |
            flu build-docker-diff --tag $GITHUB_SHA
      - name: Deploy
        id: deploy
        uses: ./scripts/actions
        with:
          command: |
            flu deploy-service-diff --tag $GITHUB_SHA
      - name: Discord notif (SUCCESS)
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Deployment succeeded.
          webhookUrl: ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }}
      - name: Discord notif (SUCCESS)
        if: cancelled()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Deployment cancelled.
          webhookUrl: ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }}
      - name: Discord notif (SUCCESS)
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Deployment failed.
          webhookUrl: ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }}


