name: Frontend CI

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: mainnet

jobs:
  codecov:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  get-diff:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: mainnet
    outputs:
      file_exists: ${{ steps.deployment_list.outputs.exist }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - name: Get Diff
        id: diff
        uses: ./scripts/actions
        with:
          command: |
            flu get-diff --environment $ENVIRONMENT --tag $GITHUB_SHA
      - uses: actions/upload-artifact@v3
        with:
          name: diff-artifact
          path: ./deployment_list.json
      - name: Check if deployment data exist
        id: deployment_list
        run: |
          if [[ -f "./deployment_list.json" ]]; then
            echo "exist=true" >> $GITHUB_OUTPUT
          fi

  deploy-web:
    if: needs.get-diff.outputs.file_exists == 'true'
    runs-on: ubuntu-latest
    environment: mainnet
    needs: [get-diff]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - uses: actions/download-artifact@v3
        with:
          name: diff-artifact
      - name: Build
        id: build
        uses: ./scripts/actions
        with:
          command: |
            flu build-diff --network fluidity --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Deploy
        id: deploy
        uses: ./scripts/actions
        with:
          command: |
            flu deploy-diff --network fluidity --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Discord
        uses: ./scripts/actions
        if: always()
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          command: |
            flu send-discord --webhook-url ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }} --status ${{ job.status }}

