name: Frontend CI

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: mainnet

jobs:
  cut-lib-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true
          token: ${{ secrets.GH_SUPER_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build changed dependencies
        uses: technote-space/get-diff-action@v6
        id: lib_diff
        with:
          PATTERNS: "web/surfing/**/*"
      - name: Build & Bump Surfing
        if: steps.lib_diff.outputs.diff
        working-directory: web/surfing
        run: |
          npm install
          npm run build
          npm version patch
      - uses: actions/setup-node@v3
        if: steps.lib_diff.outputs.diff
      - name: Publish Surfing
        if: steps.lib_diff.outputs.diff
        working-directory: web/surfing
        run: |
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm publish
      - name: Update version (Fluidity Landing)
        if: steps.lib_diff.outputs.diff
        working-directory: web/fluidity.money
        run: |
          npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install
          npm update surfing
      - name: Commit changed
        if: steps.lib_diff.outputs.diff
        run: |
          git add .
          git config user.name "Bump Bot 🤖"
          git config user.email "noreply@fluidity.money"
          git commit -m "Bump Surfing version"
          git push origin develop

  get-diff:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: mainnet
    outputs:
      file_exists: ${{ steps.deployment_list.outputs.exist }} 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - name: Get Diff
        id: diff
        uses: ./scripts/actions
        with:
          command: |
            flu get-diff --environment $ENVIRONMENT --tag $GITHUB_SHA
      - uses: actions/upload-artifact@v3
        with:
          name: diff-artifact
          path: ./deployment_list.json
      - name: Check if deployment data exist
        id: deployment_list
        run: |
          if [[ -f "./deployment_list.json" ]]; then
            echo "exist=true" >> $GITHUB_OUTPUT
          fi

  deploy-web:
    if: needs.get-diff.outputs.file_exists == 'true'
    runs-on: ubuntu-latest
    environment: mainnet
    needs: [get-diff]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - uses: actions/download-artifact@v3
        with:
          name: diff-artifact
      - name: Build
        id: build
        uses: ./scripts/actions
        with:
          command: |
            flu build-diff --network fluidity --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Deploy
        id: deploy
        uses: ./scripts/actions
        with:
          command: |
            flu deploy-diff --network fluidity --environment $ENVIRONMENT --tag $GITHUB_SHA
      - name: Save
        uses: ./scripts/actions
        if: success()
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with: 
          command: |
            flu save-info
      - name: Discord
        uses: ./scripts/actions
        if: always()
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with: 
          command: |
            flu send-discord --webhook-url ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }} --status ${{ job.status }}

