name: Fluidity CI/CD (Manual)

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
        default: 'solana'
      group:
        description: 'Group'
        required: true
      service:
        description: 'Service'
        required: true
      environment:
        type: choice
        description: 'Environment'
        options: 
          - 'dev'
      build_base:
        type: boolean
        description: 'Build base image'
        default: false
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::802019692967:role/fluidity.app.github.oidc.role
      - name: Build
        uses: ./scripts/actions
        with:
          command: |
            flu build-docker --project "${{ github.event.inputs.project }}" --group "${{ github.event.inputs.group }}" --service "${{ github.event.inputs.service }}" --environment "${{ github.event.inputs.environment }}" --tag $GITHUB_SHA --build-common "${{ github.event.inputs.build_base }}"
      - name: Deploy
        uses: ./scripts/actions
        with:
          command: |
            flu deploy-service --project "${{ github.event.inputs.project }}" --group "${{ github.event.inputs.group }}" --service "${{ github.event.inputs.service }}" --environment "${{ github.event.inputs.environment }}" --tag $GITHUB_SHA --debug false


