name: Fluidity CI/CD (Test Project)

on:
  push:
    branches:
      - develop-devops
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::802019692967:role/fluidity.app.github.oidc.role
      - name: Build
        uses: ./scripts/actions
        with:
          command: |
            flu build-docker --project solana --group all --service all --environment dev --tag $GITHUB_SHA --build-common false
      - name: Deploy
        uses: ./scripts/actions
        with:
          command: |
            flu deploy-service --project solana --group all --service all --environment dev --tag $GITHUB_SHA --debug false


