name: Rollback (Beta)

on:
  workflow_dispatch:
    inputs:
      rollbackTo:
        type: string
        description: 'Full SHA'
        required: true
      environment:
        type: choice
        description: 'Environment'
        options:
          - 'mainnet'
          - 'dev'

permissions:
  id-token: write
  contents: read

jobs:
  rollback-app:
    if: ${{ github.event.inputs.skip_app_rollback == 'false' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          ref: ${{ github.event.inputs.rollbackTo }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.FLU_AWS_GITHUB_OIDC_ROLE }}
          role-duration-seconds: 7200 #seconds
      - name: Display Commit Hash
        run: |
          echo ""
          echo "CommitHash: $(git log -1 --format='%H')"
          echo ""
      - name: Rollback App
        id: rollback
        uses: ./scripts/actions
        with:
          command: |
            flu rollback-app \
              --rollback-id ${{ github.event.inputs.rollbackTo }}
      - name: Discord
        uses: ./scripts/actions
        if: always()
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with: 
          command: |
            flu send-discord --webhook-url ${{ secrets.FLU_CI_DISCORD_WEBHOOK_URL }} --status ${{ job.status }}

